mkdir "3DO\3DO Interactive Multiplayer\Catalogs"
mkdir "3DO\3DO Interactive Multiplayer\Magazines\3DO Magazine"
mkdir "3DO\3DO Interactive Multiplayer\Magazines\Discovery 3DO (IT)"
mkdir "3DO\3DO Interactive Multiplayer\Manuals\Adult"
mkdir "3DO\3DO Interactive Multiplayer\Manuals\Applications"
mkdir "3DO\3DO Interactive Multiplayer\Manuals\Educational"
mkdir "3DO\3DO Interactive Multiplayer\Manuals\Games"
mkdir "3DO\3DO Interactive Multiplayer\Manuals\Hardware"
mkdir "3DO\3DO Interactive Multiplayer\Manuals\Multimedia"
mkdir "3DO\3DO Interactive Multiplayer\Manuals\Samplers"
mkdir "Acorn\Magazines\Acorn Action"
mkdir "Acorn\Magazines\Acorn Programs"
mkdir "Acorn\Magazines\Acorn User"
mkdir "Acorn\Magazines\Let's Compute"
mkdir "Acorn\Magazines\Micro User, The"
mkdir "Acorn\Newsletters\Acorn Education News"
mkdir "Acorn\Newsletters\Acorn Engineering News"
mkdir "Acorn\Newsletters\Acorn Higher Education News"
mkdir "Acorn\Newsletters\Acorn Newsletter"
mkdir "Acorn\Newsletters\Archimedean"
mkdir "Acorn\Archimedes\Catalogs\Hardware"
mkdir "Acorn\Archimedes\Magazines\Risc User"
mkdir "Acorn\Archimedes\Manuals\Games"
mkdir "Acorn\Archimedes\Manuals\Technical"
mkdir "Acorn\Atom\Manuals\Technical"
mkdir "Acorn\BBC\Books"
mkdir "Acorn\BBC\Magazines\Beebon, The"
mkdir "Acorn\BBC\Magazines\ByteBack"
mkdir "Acorn\BBC\Magazines\Laserbug"
mkdir "Acorn\BBC\Manuals\Games"
mkdir "Acorn\BBC\Manuals\Hardware"
mkdir "Acorn\BBC\Manuals\Technical"
mkdir "Acorn\Electron\Magazines\ELBUG"
mkdir "Acorn\Electron\Magazines\Electron User"
mkdir "Acorn\Electron\Manuals\Applications"
mkdir "Acorn\Electron\Manuals\Hardware"
mkdir "Acorn\System 1\Catalogs"
mkdir "Acorn\System 1\Manuals\Hardware"
mkdir "Acorn\System 1\Manuals\Technical"
mkdir "ACT\Apricot\Magazines\UserPrompt"
mkdir "ACT\Apricot\Manuals\Technical"
mkdir "ACT\Apricot F1\Manuals\Hardware"
mkdir "ACT\Apricot Portable\Books"
mkdir "Amstrad\Books"
mkdir "Amstrad\Magazines\Amstrad Action"
mkdir "Amstrad\Magazines\Amstrad Semanal (ES)"
mkdir "Amstrad\Magazines\Amtix"
mkdir "Amstrad\Magazines\Mundo Amstrad (ES)"
mkdir "Amstrad\Manuals\Hardware"
mkdir "Amstrad\CPC\Books"
mkdir "Amstrad\CPC\Catalogs\Games"
mkdir "Amstrad\CPC\Catalogs\Hardware"
mkdir "Amstrad\CPC\Commercials\Hardware"
mkdir "Amstrad\CPC\Magazines\Amstrad Computer User"
mkdir "Amstrad\CPC\Magazines\CPC Attack"
mkdir "Amstrad\CPC\Manuals\Applications"
mkdir "Amstrad\CPC\Manuals\Games"
mkdir "Amstrad\CPC\Manuals\Hardware"
mkdir "Amstrad\CPC\Manuals\Technical"
mkdir "Amstrad\GX4000\Artwork\Games"
mkdir "Amstrad\GX4000\Manuals\Games"
mkdir "Amstrad\GX4000\Manuals\Hardware"
mkdir "Amstrad\PCW\Magazines\8000 Plus"
mkdir "APF\Imagination Machine\Books"
mkdir "APF\Imagination Machine\Manuals\Applications"
mkdir "APF\Imagination Machine\Manuals\Catalogs"
mkdir "APF\Imagination Machine\Manuals\Games"
mkdir "APF\Imagination Machine\Manuals\Hardware"
mkdir "APF\Imagination Machine\Manuals\Software"
mkdir "APF\Imagination Machine\Manuals\Technical"
mkdir "APF\PeCos One\Manuals\Hardware"
mkdir "Apple\Books"
mkdir "Apple\Magazines\Apple 2000"
mkdir "Apple\Magazines\Apple Magazine"
mkdir "Apple\Magazines\Applicando (IT)"
mkdir "Apple\Magazines\Australian Apple Review, The"
mkdir "Apple\Magazines\COMPUTE!'s Apple Applications"
mkdir "Apple\Magazines\Hardcore"
mkdir "Apple\Magazines\Tap the iPhone and iPad Magazine"
mkdir "Apple\Manuals\Applications"
mkdir "Apple\Manuals\Technical"
mkdir "Apple\1\Catalogs"
mkdir "Apple\1\Manuals\Hardware"
mkdir "Apple\II\Books"
mkdir "Apple\II\Magazines\COMPUTIST"
mkdir "Apple\II\Magazines\Contact"
mkdir "Apple\II\Magazines\Golden"
mkdir "Apple\II\Magazines\Windfall"
mkdir "Apple\II\Manuals\Applications"
mkdir "Apple\II\Manuals\Games"
mkdir "Apple\II\Manuals\Hardware"
mkdir "Apple\II\Manuals\Technical"
mkdir "Apple\II\Newsletters\Shareware Solutions II"
mkdir "Apple\II\Newsletters\Sourceror's Apprentice, The"
mkdir "Apple\IIGS\Books"
mkdir "Apple\IIGS\Manuals\Hardware"
mkdir "Apple\III\Books"
mkdir "Apple\III\Catalogs"
mkdir "Apple\III\Magazines\On Three"
mkdir "Apple\III\Manuals\Hardware"
mkdir "Apple\III\Newsletters\Dimensions"
mkdir "Apple\iPad\Books"
mkdir "Apple\Lisa\Manuals\Hardware"
mkdir "Apple\Lisa\Manuals\Technical"
mkdir "Apple\Macintosh\Books"
mkdir "Apple\Macintosh\Catalogs"
mkdir "Apple\Macintosh\Commercials\Hardware"
mkdir "Apple\Macintosh\Magazines\Australian Macworld"
mkdir "Apple\Macintosh\Magazines\Mac Fan (JP)"
mkdir "Apple\Macintosh\Magazines\MacFormat"
mkdir "Apple\Macintosh\Magazines\MacLife (DE)"
mkdir "Apple\Macintosh\Magazines\Maclife"
mkdir "Apple\Macintosh\Magazines\MacUser"
mkdir "Apple\Macintosh\Magazines\Macworld"
mkdir "Apple\Macintosh\Magazines\Macworld UK"
mkdir "Apple\Macintosh\Manuals\Technical"
mkdir "Apple\Macintosh\Video"
mkdir "Applied Technology\MicroBee\Manuals\Applications"
mkdir "Atari\Comics\Atari Force"
mkdir "Atari\Comics\Various"
mkdir "Atari\Magazines\ANALOG Computing"
mkdir "Atari\Magazines\Antic the ATARI Resource"
mkdir "Atari\Magazines\Atari Age"
mkdir "Atari\Magazines\Atari Club (DE)"
mkdir "Atari\Magazines\Atari Connection"
mkdir "Atari\Magazines\Atari Explorer"
mkdir "Atari\Magazines\ATARI News (IT)"
mkdir "Atari\Magazines\Atari User (GB)"
mkdir "Atari\Magazines\Atarian"
mkdir "Atari\Magazines\AtariUser"
mkdir "Atari\Magazines\Input Output"
mkdir "Atari\Magazines\L'Atarien (FR)"
mkdir "Atari\Magazines\La rivista di ATARI (IT)"
mkdir "Atari\Magazines\New Atari User"
mkdir "Atari\Magazines\Winning at Videogames"
mkdir "Atari\Newsletters\Atari Age"
mkdir "Atari\2600 & VCS\Catalogs"
mkdir "Atari\2600 & VCS\Commercials\Games"
mkdir "Atari\2600 & VCS\Commercials\Hardware"
mkdir "Atari\2600 & VCS\Manuals\Applications"
mkdir "Atari\2600 & VCS\Manuals\Educational"
mkdir "Atari\2600 & VCS\Manuals\Games"
mkdir "Atari\2600 & VCS\Manuals\Hardware"
mkdir "Atari\2600 & VCS\Manuals\Technical"
mkdir "Atari\2600 & VCS\Newsletters\Activisions"
mkdir "Atari\2600 & VCS\Newsletters\Atari VCS Owners Club Bulletin"
mkdir "Atari\2600 & VCS\TV Series\Once Upon Atari (US)"
mkdir "Atari\2600 & VCS\Video"
mkdir "Atari\5200\Manuals\Games"
mkdir "Atari\5200\Manuals\Hardware"
mkdir "Atari\5200\Overlays\Games"
mkdir "Atari\7800\Commercials\Hardware"
mkdir "Atari\7800\Manuals\Games"
mkdir "Atari\7800\Manuals\Hardware"
mkdir "Atari\8bit\Books"
mkdir "Atari\8bit\Catalogs"
mkdir "Atari\8bit\Magazines\Atari Explorer"
mkdir "Atari\8bit\Magazines\ROM"
mkdir "Atari\8bit\Manuals\Applications"
mkdir "Atari\8bit\Manuals\Games"
mkdir "Atari\8bit\Manuals\Hardware"
mkdir "Atari\Jaguar\Manuals\Games"
mkdir "Atari\Jaguar CD\Manuals\Games"
mkdir "Atari\Jaguar CD\Manuals\Overlays"
mkdir "Atari\Lynx\Books"
mkdir "Atari\Lynx\Manuals\Games"
mkdir "Atari\ST\Books"
mkdir "Atari\ST\Catalogs"
mkdir "Atari\ST\Magazines\Atari ST Review"
mkdir "Atari\ST\Magazines\Atari ST User"
mkdir "Atari\ST\Magazines\Atari STen (SE)"
mkdir "Atari\ST\Magazines\Atari World"
mkdir "Atari\ST\Magazines\COMPUTE!'s Atari ST"
mkdir "Atari\ST\Magazines\One for ST Games, The"
mkdir "Atari\ST\Magazines\ST Action"
mkdir "Atari\ST\Magazines\ST Format"
mkdir "Atari\ST\Magazines\ST Magazine (FR)"
mkdir "Atari\ST\Magazines\ST-Log"
mkdir "Atari\ST\Magazines\STart"
mkdir "Atari\ST\Manuals\Games"
mkdir "Atari\ST\Manuals\Hardware"
mkdir "Atari\ST\Manuals\Technical"
mkdir "Bally\Professional Arcade & Astrocade\Manuals\Games"
mkdir "Bally\Professional Arcade & Astrocade\Manuals\Hardware"
mkdir "Bandai\Playdia\Artwork\Games"
mkdir "Bandai\Playdia\Manuals\Games"
mkdir "Bandai\Playdia\Manuals\Hardware"
mkdir "Bit Corporation\Gamate\Manuals\Games"
mkdir "Bit Corporation\Gamate\Manuals\Hardware"
mkdir "Bondwell\2\Manuals\Technical"
mkdir "Canon\Cat\Manuals\Applications"
mkdir "Canon\Cat\Manuals\Hardware"
mkdir "Canon\Cat\Manuals\Technical"
mkdir "Casio\PB-1000\Books"
mkdir "Coleco\ColecoVision\Artwork\Games"
mkdir "Coleco\ColecoVision\Catalogs"
mkdir "Coleco\ColecoVision\Commercials\Hardware"
mkdir "Coleco\ColecoVision\Magazines\ColecoVision Experience"
mkdir "Coleco\ColecoVision\Manuals\Educational"
mkdir "Coleco\ColecoVision\Manuals\Games"
mkdir "Coleco\ColecoVision\Manuals\Hardware"
mkdir "Coleco\ColecoVision\Overlays\Games"
mkdir "Coleco\ColecoVision ADAM\Manuals\Applications"
mkdir "Coleco\ColecoVision ADAM\Manuals\Educational"
mkdir "Coleco\ColecoVision ADAM\Manuals\Games"
mkdir "Coleco\ColecoVision ADAM\Manuals\Hardware"
mkdir "Commodore\Books"
mkdir "Commodore\Commercials\Hardware"
mkdir "Commodore\Magazines\Ahoy!"
mkdir "Commodore\Magazines\Club Commodore (ES)"
mkdir "Commodore\Magazines\Commander"
mkdir "Commodore\Magazines\Commodore (IT)"
mkdir "Commodore\Magazines\Commodore Computer Club (IT)"
mkdir "Commodore\Magazines\Commodore Computing International"
mkdir "Commodore\Magazines\Commodore Disk User"
mkdir "Commodore\Magazines\Commodore Fan Gazette (IT)"
mkdir "Commodore\Magazines\Commodore Gazette (IT)"
mkdir "Commodore\Magazines\Commodore Horizons"
mkdir "Commodore\Magazines\Commodore Magazine (AU)"
mkdir "Commodore\Magazines\Commodore Magazine"
mkdir "Commodore\Magazines\Commodore Microcomputers"
mkdir "Commodore\Magazines\Commodore Power-Play"
mkdir "Commodore\Magazines\Commodore Vilag (HU)"
mkdir "Commodore\Magazines\Commodore World"
mkdir "Commodore\Magazines\COMPUTE!'s Gazette"
mkdir "Commodore\Magazines\Conoscere il Computer direttamente dal computer (IT)"
mkdir "Commodore\Magazines\Dator Magazine (SE)"
mkdir "Commodore\Magazines\dieHard"
mkdir "Commodore\Magazines\Dream (FR)"
mkdir "Commodore\Magazines\geoVision International"
mkdir "Commodore\Magazines\geoWorld Magazine"
mkdir "Commodore\Magazines\Go Games (IT)"
mkdir "Commodore\Magazines\Guide to Computer Living"
mkdir "Commodore\Magazines\IC RUN (DK)"
mkdir "Commodore\Magazines\Info"
mkdir "Commodore\Magazines\Re-RUN"
mkdir "Commodore\Magazines\RUN"
mkdir "Commodore\Magazines\Transactor"
mkdir "Commodore\Magazines\Your 64"
mkdir "Commodore\Magazines\Your Commodore"
mkdir "Commodore\Magazines\Zzap!"
mkdir "Commodore\Newsletters\A.C.E.S."
mkdir "Commodore\Newsletters\Berkeley GEOS News"
mkdir "Commodore\Newsletters\CHUG Gazette"
mkdir "Commodore\Newsletters\CPU"
mkdir "Commodore\Newsletters\Eight Bit Bosters"
mkdir "Commodore\Newsletters\Feedback (AU)"
mkdir "Commodore\Newsletters\geoJournal"
mkdir "Commodore\Newsletters\geoNews"
mkdir "Commodore\Amiga\Artwork\Video"
mkdir "Commodore\Amiga\Books"
mkdir "Commodore\Amiga\Catalogs"
mkdir "Commodore\Amiga\CD\Manuals\Games"
mkdir "Commodore\Amiga\Commercials\Hardware"
mkdir "Commodore\Amiga\Magazines\AC's Guide To The Commodore Amiga"
mkdir "Commodore\Amiga\Magazines\AC's TECH For The Commodore Amiga"
mkdir "Commodore\Amiga\Magazines\Ahoy!'s AmigaUser"
mkdir "Commodore\Amiga\Magazines\Amazing Computing"
mkdir "Commodore\Amiga\Magazines\Amiga Action"
mkdir "Commodore\Amiga\Magazines\Amiga Advis (DK)"
mkdir "Commodore\Amiga\Magazines\Amiga Byte (IT)"
mkdir "Commodore\Amiga\Magazines\Amiga Computing"
mkdir "Commodore\Amiga\Magazines\Amiga Computing US Edition"
mkdir "Commodore\Amiga\Magazines\Amiga Down Under"
mkdir "Commodore\Amiga\Magazines\Amiga Fever (DE)"
mkdir "Commodore\Amiga\Magazines\Amiga Force"
mkdir "Commodore\Amiga\Magazines\Amiga Format"
mkdir "Commodore\Amiga\Magazines\Amiga Game Zone"
mkdir "Commodore\Amiga\Magazines\Amiga Games (DE)"
mkdir "Commodore\Amiga\Magazines\Amiga Informer, The"
mkdir "Commodore\Amiga\Magazines\Amiga Insider (DE)"
mkdir "Commodore\Amiga\Magazines\Amiga Interface (DK)"
mkdir "Commodore\Amiga\Magazines\Amiga Joker (DE)"
mkdir "Commodore\Amiga\Magazines\Amiga Magazine (IT)"
mkdir "Commodore\Amiga\Magazines\Amiga News"
mkdir "Commodore\Amiga\Magazines\Amiga Point of View"
mkdir "Commodore\Amiga\Magazines\Amiga Power"
mkdir "Commodore\Amiga\Magazines\Amiga Shopper"
mkdir "Commodore\Amiga\Magazines\Amiga User International"
mkdir "Commodore\Amiga\Magazines\Amiga World"
mkdir "Commodore\Amiga\Magazines\AmigActive"
mkdir "Commodore\Amiga\Magazines\AmigaUser"
mkdir "Commodore\Amiga\Magazines\AmigaWorld"
mkdir "Commodore\Amiga\Magazines\AmigaWorld Tech Journal"
mkdir "Commodore\Amiga\Magazines\Antic's AMIGA Plus"
mkdir "Commodore\Amiga\Magazines\Australian Commodore and Amiga Review, The"
mkdir "Commodore\Amiga\Magazines\Bitplane (IT)"
mkdir "Commodore\Amiga\Magazines\Blitz User (NZ)"
mkdir "Commodore\Amiga\Magazines\COMPUTE!'s Amiga Resource"
mkdir "Commodore\Amiga\Magazines\CU Amiga"
mkdir "Commodore\Amiga\Magazines\Enigma Amiga Life (IT)"
mkdir "Commodore\Amiga\Magazines\One, The"
mkdir "Commodore\Amiga\Magazines\OZAmiga Magazine"
mkdir "Commodore\Amiga\Magazines\Professional Amiga User Magazine"
mkdir "Commodore\Amiga\Magazines\Total Amiga"
mkdir "Commodore\Amiga\Magazines\Workbench"
mkdir "Commodore\Amiga\Manuals\Applications"
mkdir "Commodore\Amiga\Manuals\Educational"
mkdir "Commodore\Amiga\Manuals\Games"
mkdir "Commodore\Amiga\Manuals\Hardware"
mkdir "Commodore\Amiga\Manuals\Technical"
mkdir "Commodore\Amiga\Newsletters\Argonauts"
mkdir "Commodore\Amiga\Video"
mkdir "Commodore\Amiga CD32\Artwork\Games"
mkdir "Commodore\Amiga CD32\Catalogs"
mkdir "Commodore\Amiga CD32\Commercials\Hardware"
mkdir "Commodore\Amiga CD32\Magazines\Amiga CD32"
mkdir "Commodore\Amiga CD32\Magazines\Amiga CD32 Gamer"
mkdir "Commodore\Amiga CD32\Manuals\Games"
mkdir "Commodore\Amiga CD32\Manuals\Hardware"
mkdir "Commodore\Amiga CD32\Manuals\Technical"
mkdir "Commodore\Amiga CDTV\Artwork\Games"
mkdir "Commodore\Amiga CDTV\Catalogs"
mkdir "Commodore\Amiga CDTV\Manuals\Educational"
mkdir "Commodore\Amiga CDTV\Manuals\Games"
mkdir "Commodore\Amiga CDTV\Manuals\Hardware"
mkdir "Commodore\Amiga CDTV\Manuals\Technical"
mkdir "Commodore\C128\Books"
mkdir "Commodore\C128\Commercials\Hardware"
mkdir "Commodore\C128\Manuals\Applications"
mkdir "Commodore\C128\Manuals\Hardware"
mkdir "Commodore\C128\Manuals\Technical"
mkdir "Commodore\C128\Video"
mkdir "Commodore\C16, C116 & Plus-4\Books"
mkdir "Commodore\C16, C116 & Plus-4\Catalogs"
mkdir "Commodore\C16, C116 & Plus-4\Magazines\C16 C116 Plus4 Computing Monthly"
mkdir "Commodore\C16, C116 & Plus-4\Magazines\C16 Plus 4 Handbook"
mkdir "Commodore\C16, C116 & Plus-4\Manuals\Applications"
mkdir "Commodore\C16, C116 & Plus-4\Manuals\Educational"
mkdir "Commodore\C16, C116 & Plus-4\Manuals\Games"
mkdir "Commodore\C16, C116 & Plus-4\Manuals\Hardware"
mkdir "Commodore\C16, C116 & Plus-4\Manuals\Technical"
mkdir "Commodore\C16, C116 & Plus-4\Newsletters\Newsplug"
mkdir "Commodore\C16, C116 & Plus-4\Newsletters\Plus Exchange"
mkdir "Commodore\C16, C116 & Plus-4\Video"
mkdir "Commodore\C64\Books"
mkdir "Commodore\C64\Catalogs\Applications"
mkdir "Commodore\C64\Catalogs\Hardware"
mkdir "Commodore\C64\Commercials\Hardware"
mkdir "Commodore\C64\Magazines\7 Note Bit (IT)"
mkdir "Commodore\C64\Magazines\Cevi-Aktuell (DE)"
mkdir "Commodore\C64\Magazines\Commodore Format"
mkdir "Commodore\C64\Magazines\Dream (IT)"
mkdir "Commodore\C64\Magazines\GO64!"
mkdir "Commodore\C64\Magazines\Hit Parade (IT)"
mkdir "Commodore\C64\Magazines\INPUT Commodore (ES)"
mkdir "Commodore\C64\Magazines\SIDin"
mkdir "Commodore\C64\Magazines\Top Playgames (IT)"
mkdir "Commodore\C64\Magazines\Video Basic Imparare col C64 (IT)"
mkdir "Commodore\C64\Manuals\Applications"
mkdir "Commodore\C64\Manuals\Educational"
mkdir "Commodore\C64\Manuals\Games"
mkdir "Commodore\C64\Manuals\Hardware"
mkdir "Commodore\C64\Manuals\Technical"
mkdir "Commodore\C64\Video"
mkdir "Commodore\PET\Books"
mkdir "Commodore\PET\Catalogs"
mkdir "Commodore\PET\Magazines\Pocket PET (IT)"
mkdir "Commodore\PET\Magazines\TORPET, The"
mkdir "Commodore\PET\Manuals\Hardware"
mkdir "Commodore\VIC20\Books"
mkdir "Commodore\VIC20\Catalogs"
mkdir "Commodore\VIC20\Magazines\VICTape Computing"
mkdir "Commodore\VIC20\Manuals\Applications"
mkdir "Commodore\VIC20\Manuals\Educational"
mkdir "Commodore\VIC20\Manuals\Games"
mkdir "Commodore\VIC20\Manuals\Hardware"
mkdir "Commodore\VIC20\Manuals\Technical"
mkdir "Dick Smith\System 80\Books"
mkdir "Dick Smith\System 80\Catalogs"
mkdir "Dick Smith\System 80\Manuals\Hardware"
mkdir "Dick Smith\System 80\Manuals\Technical"
mkdir "Dragon Data\Dragon\Books"
mkdir "Dragon Data\Dragon\Magazines\Cuthbert Chronicles, The"
mkdir "Dragon Data\Dragon\Magazines\Dragon Stop Press"
mkdir "Dragon Data\Dragon\Magazines\Dragon User"
mkdir "Dragon Data\Dragon\Magazines\Dragon World"
mkdir "Dragon Data\Dragon\Manuals\Games"
mkdir "EACA\EG2000 Colour Genie\Books"
mkdir "EACA\EG2000 Colour Genie\Manuals\Applications"
mkdir "EACA\EG2000 Colour Genie\Manuals\Games"
mkdir "EACA\EG2000 Colour Genie\Manuals\Hardware"
mkdir "EACA\EG2000 Colour Genie\Manuals\Technical"
mkdir "Entex\Adventure Vision\Manuals\Games"
mkdir "Entex\Adventure Vision\Manuals\Hardware"
mkdir "Exidy\Sorcerer\Books"
mkdir "Exidy\Sorcerer\Catalogs"
mkdir "Exidy\Sorcerer\Magazines\Sorcerers Apprentice, The"
mkdir "Exidy\Sorcerer\Manuals\Applications"
mkdir "Exidy\Sorcerer\Manuals\Hardware"
mkdir "Exidy\Sorcerer\Manuals\Technical"
mkdir "Fairchild\VES & Channel F\Manuals\Games"
mkdir "Fairchild\VES & Channel F\Manuals\Hardware"
mkdir "Franklin\ACE 100\Manuals\Hardware"
mkdir "Franklin\ACE 1000\Manuals\Hardware"
mkdir "Franklin\ACE 2000\Manuals\Hardware"
mkdir "Franklin\ACE 500\Manuals\Hardware"
mkdir "GCE\Vectrex\Catalogs"
mkdir "GCE\Vectrex\Commercials\Hardware"
mkdir "GCE\Vectrex\Manuals\Applications"
mkdir "GCE\Vectrex\Manuals\Games"
mkdir "GCE\Vectrex\Manuals\Hardware"
mkdir "GCE\Vectrex\Manuals\Technical"
mkdir "HomeLab\BraiLab\Books (HU)"
mkdir "HomeLab\HomeLab\Manuals\Hardware (HU)"
mkdir "HomeLab\HomeLab\Manuals\Software (HU)"
mkdir "IBM\PC Compatibles\Artwork\Games"
mkdir "IBM\PC Compatibles\Books"
mkdir "IBM\PC Compatibles\Catalogs\Applications"
mkdir "IBM\PC Compatibles\Catalogs\Games"
mkdir "IBM\PC Compatibles\Catalogs\Hardware"
mkdir "IBM\PC Compatibles\Commercials\Applications"
mkdir "IBM\PC Compatibles\Commercials\Games"
mkdir "IBM\PC Compatibles\Commercials\Hardware"
mkdir "IBM\PC Compatibles\Magazines\.psd Magazine"
mkdir "IBM\PC Compatibles\Magazines\3D World"
mkdir "IBM\PC Compatibles\Magazines\Atomic"
mkdir "IBM\PC Compatibles\Magazines\Australian Netguide"
mkdir "IBM\PC Compatibles\Magazines\Australian PC User"
mkdir "IBM\PC Compatibles\Magazines\Australian Personal Computer (AU)"
mkdir "IBM\PC Compatibles\Magazines\Bestseller Games (DE)"
mkdir "IBM\PC Compatibles\Magazines\BugBug (JP)"
mkdir "IBM\PC Compatibles\Magazines\Chips 'n' Bits"
mkdir "IBM\PC Compatibles\Magazines\COMPUTE!'s PC Magazine"
mkdir "IBM\PC Compatibles\Magazines\Computer Active (IN)"
mkdir "IBM\PC Compatibles\Magazines\Computer Active"
mkdir "IBM\PC Compatibles\Magazines\Computer Arts (CN)"
mkdir "IBM\PC Compatibles\Magazines\Computer Arts (GB)"
mkdir "IBM\PC Compatibles\Magazines\Computer Gaming World"
mkdir "IBM\PC Compatibles\Magazines\Computer Living"
mkdir "IBM\PC Compatibles\Magazines\Computer Power User"
mkdir "IBM\PC Compatibles\Magazines\Computer Shopper (GB)"
mkdir "IBM\PC Compatibles\Magazines\Computer Shopper (US)"
mkdir "IBM\PC Compatibles\Magazines\Custom PC"
mkdir "IBM\PC Compatibles\Magazines\dot net"
mkdir "IBM\PC Compatibles\Magazines\Easy PC"
mkdir "IBM\PC Compatibles\Magazines\Free Access"
mkdir "IBM\PC Compatibles\Magazines\Full Circle"
mkdir "IBM\PC Compatibles\Magazines\Games For Windows"
mkdir "IBM\PC Compatibles\Magazines\Just Magazines Computer Market"
mkdir "IBM\PC Compatibles\Magazines\Maximum PC"
mkdir "IBM\PC Compatibles\Magazines\Microsoft Windows XP Magazine"
mkdir "IBM\PC Compatibles\Magazines\Net, The"
mkdir "IBM\PC Compatibles\Magazines\PC & Tech Authority"
mkdir "IBM\PC Compatibles\Magazines\PC Advisor"
mkdir "IBM\PC Compatibles\Magazines\PC Answers"
mkdir "IBM\PC Compatibles\Magazines\PC Computing"
mkdir "IBM\PC Compatibles\Magazines\PC Format"
mkdir "IBM\PC Compatibles\Magazines\PC Gamer (GB)"
mkdir "IBM\PC Compatibles\Magazines\PC Gamer (US)"
mkdir "IBM\PC Compatibles\Magazines\PC Games (DE)"
mkdir "IBM\PC Compatibles\Magazines\PC Games (US)"
mkdir "IBM\PC Compatibles\Magazines\PC Magazine"
mkdir "IBM\PC Compatibles\Magazines\PC Master (GR)"
mkdir "IBM\PC Compatibles\Magazines\PC Player (DE)"
mkdir "IBM\PC Compatibles\Magazines\PC Player (GB)"
mkdir "IBM\PC Compatibles\Magazines\PC Plus"
mkdir "IBM\PC Compatibles\Magazines\PC Powerplay"
mkdir "IBM\PC Compatibles\Magazines\PC Pro"
mkdir "IBM\PC Compatibles\Magazines\PC Professionale (IT)"
mkdir "IBM\PC Compatibles\Magazines\PC Review"
mkdir "IBM\PC Compatibles\Magazines\PC Today"
mkdir "IBM\PC Compatibles\Magazines\PC World"
mkdir "IBM\PC Compatibles\Magazines\PC Zone"
mkdir "IBM\PC Compatibles\Magazines\Personal Computer World"
mkdir "IBM\PC Compatibles\Magazines\Photoshop User"
mkdir "IBM\PC Compatibles\Magazines\Pon-Pon (IT)"
mkdir "IBM\PC Compatibles\Magazines\Practical Photoshop"
mkdir "IBM\PC Compatibles\Magazines\Technology & Business"
mkdir "IBM\PC Compatibles\Magazines\Visual Studio Magazine"
mkdir "IBM\PC Compatibles\Magazines\Webuser"
mkdir "IBM\PC Compatibles\Magazines\What Laptop"
mkdir "IBM\PC Compatibles\Magazines\Windows 7 Help & Advice"
mkdir "IBM\PC Compatibles\Magazines\Windows The Official Magazine"
mkdir "IBM\PC Compatibles\Magazines\Your Computer"
mkdir "IBM\PC Compatibles\Manuals\Applications"
mkdir "IBM\PC Compatibles\Manuals\Games"
mkdir "IBM\PC Compatibles\Manuals\Hardware"
mkdir "IBM\PC Compatibles\Manuals\Operating Systems"
mkdir "IBM\PC Compatibles\Manuals\Technical"
mkdir "IBM\PC Compatibles\Video"
mkdir "IBM\PCjr\Books"
mkdir "IBM\PCjr\Catalogs"
mkdir "IBM\PCjr\Commercials\Hardware"
mkdir "IBM\PCjr\Manuals\Applications"
mkdir "IBM\PCjr\Manuals\Hardware"
mkdir "IBM\PCjr\Manuals\Technical"
mkdir "IBM\PCjr\Video"
mkdir "iQue\Player\Manuals\Games"
mkdir "Jupiter Cantab\Jupiter Ace\Books"
mkdir "Jupiter Cantab\Jupiter Ace\Magazines\Ace User"
mkdir "Jupiter Cantab\Jupiter Ace\Manuals\Applications"
mkdir "Jupiter Cantab\Jupiter Ace\Manuals\Hardware"
mkdir "Kaypro\Magazines\PROFILES"
mkdir "Kaypro\Manuals\Technical"
mkdir "Kaypro\II\Manuals\Hardware"
mkdir "Magnavox\Odyssey\Manuals\Hardware"
mkdir "Magnavox\Odyssey\Manuals\Software"
mkdir "Magnavox\Odyssey2\Catalogs"
mkdir "Magnavox\Odyssey2\Magazines\G7000 Video Game Club News"
mkdir "Magnavox\Odyssey2\Magazines\Odyssey 2 Adventure"
mkdir "Magnavox\Odyssey2\Magazines\Odyssey Aventura (BR)"
mkdir "Magnavox\Odyssey2\Manuals\Hardware"
mkdir "Magnavox\Odyssey2\Manuals\Software"
mkdir "Magnavox\Odyssey2\Manuals\Technical"
mkdir "Matsushita\JR-100\Manuals\Hardware"
mkdir "Mattel\HyperScan\Manuals\Games"
mkdir "Mattel\HyperScan\Manuals\Hardware"
mkdir "Mattel\Intellivision\Catalogs"
mkdir "Mattel\Intellivision\Commercials\Games"
mkdir "Mattel\Intellivision\Commercials\Hardware"
mkdir "Mattel\Intellivision\Manuals\Applications"
mkdir "Mattel\Intellivision\Manuals\Educational"
mkdir "Mattel\Intellivision\Manuals\Games"
mkdir "Mattel\Intellivision\Manuals\Hardware"
mkdir "Mattel\Intellivision\Manuals\Technical"
mkdir "Mattel\Intellivision\Newsletters\Digiplay Games (BR)"
mkdir "Mattel\Intellivision\Newsletters\Imagic Number Thumb News"
mkdir "Mattel\Intellivision\Newsletters\Intellivision Game Club News"
mkdir "Mattel\Intellivision\Overlays\Games"
mkdir "Memotech\MTX\Manuals\Hardware"
mkdir "Microdigital\Magazines\Microhobby (BR)"
mkdir "Microkey\Primo\Books (HU)"
mkdir "Microkey\Primo\Manuals\Hardware (HU)"
mkdir "Microkey\Primo\Manuals\Software (HU)"
mkdir "Microsoft\Comics\Halo"
mkdir "Microsoft\TV Series\Halo"
mkdir "Microsoft\TV Series\Halo Nightfall"
mkdir "Microsoft\TV Series\Power on\The Story of Xbox"
mkdir "Microsoft\Xbox\Artwork\Games"
mkdir "Microsoft\Xbox\Books"
mkdir "Microsoft\Xbox\Commercials\Games"
mkdir "Microsoft\Xbox\Magazines\Official XBOX Magazine (AU)"
mkdir "Microsoft\Xbox\Magazines\Official XBOX Magazine (GB)"
mkdir "Microsoft\Xbox\Manuals\Games"
mkdir "Microsoft\Xbox\Manuals\Hardware"
mkdir "Microsoft\Xbox 360\Books"
mkdir "Microsoft\Xbox 360\Commercials\Games"
mkdir "Microsoft\Xbox 360\Magazines\360 Gamer"
mkdir "Microsoft\Xbox 360\Magazines\360 Magazine"
mkdir "Microsoft\Xbox 360\Magazines\Official XBOX Magazine (GB)"
mkdir "Microsoft\Xbox 360\Magazines\Official XBOX Magazine (US)"
mkdir "Microsoft\Xbox 360\Magazines\X360 Magazine"
mkdir "Microsoft\Xbox 360\Magazines\Xbox 360 World"
mkdir "Microsoft\Xbox 360\Magazines\Xbox World"
mkdir "Microsoft\Xbox 360\Manuals\Games"
mkdir "Microsoft\Xbox 360\Manuals\Hardware"
mkdir "Microsoft\Xbox One\Commercials\Games"
mkdir "Microsoft\Xbox One\Commercials\Hardware"
mkdir "MSX\Magazines\Input MSX (ES)"
mkdir "MSX\Magazines\MSX Club (ES)"
mkdir "MSX\Magazines\MSX Computer Magazine (NL)"
mkdir "MSX\Magazines\MSX Magazine (ES)"
mkdir "MSX\Magazines\MSX Magazine (FR)"
mkdir "MSX\Magazines\MSX Magazine (JP)"
mkdir "MSX\Magazines\MSX Micro (BR)"
mkdir "MSX\Magazines\MSX Top Class (BR)"
mkdir "MSX\Magazines\MSX World (ES)"
mkdir "MSX\Magazines\MSX-FAN (JP)"
mkdir "MSX\Manuals\Technical"
mkdir "MSX\Palcom\Manuals\Games"
mkdir "Multi-format\Artbooks"
mkdir "Multi-format\Books"
mkdir "Multi-format\Catalogs"
mkdir "Multi-format\Comics\Beneath a Steel Sky (IT)"
mkdir "Multi-format\Comics\Devil May Cry"
mkdir "Multi-format\Comics\Doom"
mkdir "Multi-format\Artbooks\Girls of Anime (US)"
mkdir "Multi-format\Artbooks\Girls of Gaming (US)"
mkdir "Multi-format\Comics\Load Runner"
mkdir "Multi-format\Comics\Max Payne 3"
mkdir "Multi-format\Comics\Mirror's Edge"
mkdir "Multi-format\Comics\New Science Fair Story of Electronics, The"
mkdir "Multi-format\Comics\Perfect Dark"
mkdir "Multi-format\Comics\Resident Evil"
mkdir "Multi-format\Comics\Rival Schools"
mkdir "Multi-format\Comics\Silent Hill"
mkdir "Multi-format\Comics\Space Ace (IT)"
mkdir "Multi-format\Comics\Street Fighter"
mkdir "Multi-format\Commercials\Games"
mkdir "Multi-format\Game Guides"
mkdir "Multi-format\Magazines\300 Baud"
mkdir "Multi-format\Magazines\576KByte (HU)"
mkdir "Multi-format\Magazines\ACE"
mkdir "Multi-format\Magazines\Arcade"
mkdir "Multi-format\Magazines\Arcadia (JP)"
mkdir "Multi-format\Magazines\Ares"
mkdir "Multi-format\Magazines\Atomix (MX)"
mkdir "Multi-format\Magazines\Australian OS9 Newsletter"
mkdir "Multi-format\Magazines\Baron's MicroComputing Reports"
mkdir "Multi-format\Magazines\BBS Magazine"
mkdir "Multi-format\Magazines\BIG K"
mkdir "Multi-format\Magazines\Bit (IT)"
mkdir "Multi-format\Magazines\Bits & Bytes (NZ)"
mkdir "Multi-format\Magazines\BLIP"
mkdir "Multi-format\Magazines\Boardwatch Magazine"
mkdir "Multi-format\Magazines\BYTE"
mkdir "Multi-format\Magazines\C16-MSX (IT)"
mkdir "Multi-format\Magazines\Classic Gamer Magazine"
mkdir "Multi-format\Magazines\Code Vault"
mkdir "Multi-format\Magazines\compute II"
mkdir "Multi-format\Magazines\COMPUTE!"
mkdir "Multi-format\Magazines\Computer & Video Games"
mkdir "Multi-format\Magazines\Computer + Videogiochi (IT)"
mkdir "Multi-format\Magazines\Computer Gamer"
mkdir "Multi-format\Magazines\Computer Games (IT)"
mkdir "Multi-format\Magazines\Computer Input"
mkdir "Multi-format\Magazines\Computer Language"
mkdir "Multi-format\Magazines\Computer News PC"
mkdir "Multi-format\Magazines\Computer Play"
mkdir "Multi-format\Magazines\CPU (BR)"
mkdir "Multi-format\Magazines\Creative Computing"
mkdir "Multi-format\Magazines\Digital Press"
mkdir "Multi-format\Magazines\Dynamic Memories"
mkdir "Multi-format\Magazines\Edge (AU)"
mkdir "Multi-format\Magazines\Edge"
mkdir "Multi-format\Magazines\Electronic Fun with Computer & Games"
mkdir "Multi-format\Magazines\Electronic Games (IT)"
mkdir "Multi-format\Magazines\Electronic Games"
mkdir "Multi-format\Magazines\Electronic Gaming Monthly"
mkdir "Multi-format\Magazines\Elektor (IT)"
mkdir "Multi-format\Magazines\Enter"
mkdir "Multi-format\Magazines\Family Computing"
mkdir "Multi-format\Magazines\GAME (IT)"
mkdir "Multi-format\Magazines\Game Informer (AU)"
mkdir "Multi-format\Magazines\Game Informer (US)"
mkdir "Multi-format\Magazines\Game Insider"
mkdir "Multi-format\Magazines\GamePower (BR)"
mkdir "Multi-format\Magazines\GamePro"
mkdir "Multi-format\Magazines\Gamers (BR)"
mkdir "Multi-format\Magazines\Gamers Republic"
mkdir "Multi-format\Magazines\Games Computing"
mkdir "Multi-format\Magazines\Games Machine, The (IT)"
mkdir "Multi-format\Magazines\Games Machine, The"
mkdir "Multi-format\Magazines\Games Magazine (RU)"
mkdir "Multi-format\Magazines\Games Master"
mkdir "Multi-format\Magazines\Games of the 90's (IT)"
mkdir "Multi-format\Magazines\Giochi per il mio Computer (IT)"
mkdir "Multi-format\Magazines\Guida Video Giochi (IT)"
mkdir "Multi-format\Magazines\Hacker Journal (IT)"
mkdir "Multi-format\Magazines\Hardcore Gamer"
mkdir "Multi-format\Magazines\HC Home Computer (IT)"
mkdir "Multi-format\Magazines\Hewlett-Packard Journal"
mkdir "Multi-format\Magazines\Home Computer Magazine"
mkdir "Multi-format\Magazines\Hyper (AU)"
mkdir "Multi-format\Magazines\IGN Unplugged"
mkdir "Multi-format\Magazines\Informatica CPU (BR)"
mkdir "Multi-format\Magazines\INPUT (BR)"
mkdir "Multi-format\Magazines\Input"
mkdir "Multi-format\Magazines\InterAction Magazine"
mkdir "Multi-format\Magazines\Interface Age"
mkdir "Multi-format\Magazines\JoyStik"
mkdir "Multi-format\Magazines\K (IT)"
mkdir "Multi-format\Magazines\K-POWER"
mkdir "Multi-format\Magazines\KiloByte"
mkdir "Multi-format\Magazines\Leisure Line"
mkdir "Multi-format\Magazines\Link-Up"
mkdir "Multi-format\Magazines\LIST (IT)"
mkdir "Multi-format\Magazines\Live (AU)"
mkdir "Multi-format\Magazines\Lotek64 (DE)"
mkdir "Multi-format\Magazines\MC microcomputer (IT)"
mkdir "Multi-format\Magazines\Mean Machines"
mkdir "Multi-format\Magazines\Message of the Day"
mkdir "Multi-format\Magazines\Metamorphosis"
mkdir "Multi-format\Magazines\Micro"
mkdir "Multi-format\Magazines\Micro Adventurer"
mkdir "Multi-format\Magazines\MICRO CORNUCOPIA"
mkdir "Multi-format\Magazines\Micro Sistemas (BR)"
mkdir "Multi-format\Magazines\MICRO-80 (AU)"
mkdir "Multi-format\Magazines\MicroKids"
mkdir "Multi-format\Magazines\MMSFORTH Newsletter, The"
mkdir "Multi-format\Magazines\New Special Playgames (IT)"
mkdir "Multi-format\Magazines\NewTekniques"
mkdir "Multi-format\Magazines\Old Skool Games"
mkdir "Multi-format\Magazines\Orphaned Computer & Game Systems"
mkdir "Multi-format\Magazines\OS-9 International"
mkdir "Multi-format\Magazines\OS-9 Newsletter"
mkdir "Multi-format\Magazines\OSK'er, The"
mkdir "Multi-format\Magazines\PAPER soft (IT)"
mkdir "Multi-format\Magazines\Personal Computing Today"
mkdir "Multi-format\Magazines\Pixel (GR)"
mkdir "Multi-format\Magazines\Players (IT)"
mkdir "Multi-format\Magazines\RAZE"
mkdir "Multi-format\Magazines\Retro Gamer"
mkdir "Multi-format\Magazines\retroGAMER (IT)"
mkdir "Multi-format\Magazines\Secret File (JP)"
mkdir "Multi-format\Magazines\Sega Computer"
mkdir "Multi-format\Magazines\Silicon Chip"
mkdir "Multi-format\Magazines\SoftSide"
mkdir "Multi-format\Magazines\Special Program (IT)"
mkdir "Multi-format\Magazines\ST Amiga Format"
mkdir "Multi-format\Magazines\Stack, The"
mkdir "Multi-format\Magazines\SUPER (IT)"
mkdir "Multi-format\Magazines\SuperGamePower (BR)"
mkdir "Multi-format\Magazines\Tech Life"
mkdir "Multi-format\Magazines\Tips & Tricks"
mkdir "Multi-format\Magazines\Total Control"
mkdir "Multi-format\Magazines\TV Gamer"
mkdir "Multi-format\Magazines\ugvm"
mkdir "Multi-format\Magazines\Ultimate Future Games"
mkdir "Multi-format\Magazines\UnderColor"
mkdir "Multi-format\Magazines\UpTime"
mkdir "Multi-format\Magazines\Various"
mkdir "Multi-format\Magazines\Video & Arcade Games"
mkdir "Multi-format\Magazines\Video Games & Computer Entertainment"
mkdir "Multi-format\Magazines\Video Games (DE)"
mkdir "Multi-format\Magazines\Video Games (US)"
mkdir "Multi-format\Magazines\Video Games Player"
mkdir "Multi-format\Magazines\Videogame & Computer World (IT)"
mkdir "Multi-format\Magazines\VideoGame (BR)"
mkdir "Multi-format\Magazines\Videogaming Illustrated"
mkdir "Multi-format\Magazines\VideoGiochi & Computer (IT)"
mkdir "Multi-format\Magazines\Vidiot"
mkdir "Multi-format\Magazines\World of 68' Micros, The"
mkdir "Multi-format\Magazines\Zero"
mkdir "Multi-format\Magazines\Zeta (IT)"
mkdir "Multi-format\Magazines\Znews"
mkdir "Multi-format\Magazines\ZXShed"
mkdir "Multi-format\Magazines\Zzap! (IT)"
mkdir "Multi-format\Manuals\Games"
mkdir "Multi-format\Newsletters\New Zork Times, The"
mkdir "Multi-format\TV Series\Bits (GB)"
mkdir "Multi-format\TV Series\Bits and Bytes"
mkdir "Multi-format\TV Series\Computer Programme, The"
mkdir "Multi-format\TV Series\High Score (US)"
mkdir "Multi-format\TV Series\History of the BBS"
mkdir "Multi-format\TV Series\Icons"
mkdir "Multi-format\TV Series\Life on the Internet"
mkdir "Multi-format\TV Series\Machine that Changed the World, The"
mkdir "Multi-format\TV Series\Making the Most of the Micro"
mkdir "Multi-format\TV Series\Micro Live"
mkdir "Multi-format\TV Series\Nerds 2.0.1\A Brief History of the Internet"
mkdir "Multi-format\TV Series\Reset the Unauthorized Guide to Video Games"
mkdir "Multi-format\TV Series\Rise of the Video Game"
mkdir "Multi-format\TV Series\Top 100 Video Games of All Time (US)"
mkdir "Multi-format\TV Shows\Wordwide Gaming"
mkdir "Multi-format\Video"
mkdir "NEC\PC-9801\Artwork\Games"
mkdir "NEC\PC-9801\Manuals\Games"
mkdir "NEC\PC-Engine & TurboGrafx-16\Books"
mkdir "NEC\PC-Engine & TurboGrafx-16\Manuals\Games"
mkdir "NEC\PC-Engine & TurboGrafx-16\Manuals\Technical"
mkdir "NEC\PC-Engine & TurboGrafx-16\Video"
mkdir "NEC\PC-Engine CD & TurboGrafx-16 CD\Manuals\Games"
mkdir "NEC\PC-Engine CD & TurboGrafx-16 CD\Manuals\Hardware"
mkdir "NEC\PC-FX\Artwork\Games"
mkdir "NEC\PC-FX\Manuals\Games"
mkdir "NEC\PC-FX\Manuals\Hardware"
mkdir "Nintendo\Books"
mkdir "Nintendo\Commercials\Games"
mkdir "Nintendo\Game Boy Advance\Catalogs"
mkdir "Nintendo\Magazines\Club Nintendo (DE)"
mkdir "Nintendo\Magazines\Club Nintendo (GB)"
mkdir "Nintendo\Magazines\Club Nintendo (NL)"
mkdir "Nintendo\Magazines\N-Force"
mkdir "Nintendo\Magazines\Nintendo Gamer (AU)"
mkdir "Nintendo\Magazines\Nintendo Gamer (GB)"
mkdir "Nintendo\Magazines\Nintendo Magazine"
mkdir "Nintendo\Magazines\Nintendo Magazine System (AU)"
mkdir "Nintendo\Magazines\Nintendo Magazine System (GB)"
mkdir "Nintendo\Magazines\Nintendo Official Magazine"
mkdir "Nintendo\Magazines\Nintendo Power"
mkdir "Nintendo\Magazines\NintendoAGE"
mkdir "Nintendo\Magazines\Official Nintendo Magazine"
mkdir "Nintendo\Magazines\Planet Game Boy"
mkdir "Nintendo\Magazines\Total!"
mkdir "Nintendo\Video"
mkdir "Nintendo\3DS\Catalogs"
mkdir "Nintendo\3DS\Commercials\Games"
mkdir "Nintendo\3DS\Manuals\Games"
mkdir "Nintendo\3DS\Manuals\Hardware"
mkdir "Nintendo\64\Commercials\Games"
mkdir "Nintendo\64\Commercials\Hardware"
mkdir "Nintendo\64\Magazines\64 Extreme"
mkdir "Nintendo\64\Magazines\64 Magazine"
mkdir "Nintendo\64\Magazines\64 Solutions"
mkdir "Nintendo\64\Magazines\N64 Gamer"
mkdir "Nintendo\64\Magazines\N64 Magazine"
mkdir "Nintendo\64\Manuals\Games"
mkdir "Nintendo\64\Manuals\Hardware"
mkdir "Nintendo\64\Video"
mkdir "Nintendo\64DD\Video"
mkdir "Nintendo\DS\Catalogs"
mkdir "Nintendo\DS\Manuals\Games"
mkdir "Nintendo\DS\Manuals\Hardware"
mkdir "Nintendo\DS\Manuals\Technical"
mkdir "Nintendo\Famicom & Entertainment System\Books"
mkdir "Nintendo\Famicom & Entertainment System\Commercials\Games"
mkdir "Nintendo\Famicom & Entertainment System\Manuals\Applications"
mkdir "Nintendo\Famicom & Entertainment System\Manuals\Educational"
mkdir "Nintendo\Famicom & Entertainment System\Manuals\Games"
mkdir "Nintendo\Famicom & Entertainment System\Manuals\Hardware"
mkdir "Nintendo\Famicom & Entertainment System\Video"
mkdir "Nintendo\Famicom Disk System\Manuals\Games"
mkdir "Nintendo\Game Boy\Books"
mkdir "Nintendo\Game Boy\Commercials\Hardware"
mkdir "Nintendo\Game Boy\Video"
mkdir "Nintendo\Game Boy Advance\Books"
mkdir "Nintendo\Game Boy Advance\Magazines\GBX"
mkdir "Nintendo\Game Boy Advance\Magazines\Nintendo Power Advance"
mkdir "Nintendo\Game Boy Advance\Manuals\Games"
mkdir "Nintendo\Game Boy Advance\Manuals\Hardware"
mkdir "Nintendo\GameCube\Manuals\Games"
mkdir "Nintendo\GameCube\Manuals\Hardware"
mkdir "Nintendo\Super Famicom & Super Entertainment System\Books"
mkdir "Nintendo\Super Famicom & Super Entertainment System\Commercials\Games"
mkdir "Nintendo\Super Famicom & Super Entertainment System\Commercials\Hardware"
mkdir "Nintendo\Super Famicom & Super Entertainment System\Magazines\SNES Force"
mkdir "Nintendo\Super Famicom & Super Entertainment System\Magazines\Superplay"
mkdir "Nintendo\Super Famicom & Super Entertainment System\Manuals\Games"
mkdir "Nintendo\Super Famicom & Super Entertainment System\Manuals\Hardware"
mkdir "Nintendo\Super Famicom & Super Entertainment System\Video"
mkdir "Nintendo\Switch\Artwork\Games"
mkdir "Nintendo\Switch\Catalogs"
mkdir "Nintendo\Virtual Boy\Manuals\Games"
mkdir "Nintendo\Virtual Boy\Manuals\Hardware"
mkdir "Nintendo\Wii\Books"
mkdir "Nintendo\Wii\Catalogs"
mkdir "Nintendo\Wii\Manuals\Games"
mkdir "Nintendo\Wii U\Catalogs"
mkdir "Nintendo\Wii U\Commercials\Games"
mkdir "Nintendo\Wii U\Commercials\Hardware"
mkdir "Nintendo\Wii U\Manuals\Games"
mkdir "Nintendo\Wii U\Manuals\Hardware"
mkdir "Nokia\N-Gage\Manuals\Games"
mkdir "Philips\CD-i\Catalogs"
mkdir "Philips\CD-i\Magazines\CD Interactief (NL)"
mkdir "Philips\CD-i\Magazines\CD-i Magazine"
mkdir "Philips\CD-i\Manuals\Educational"
mkdir "Philips\CD-i\Manuals\Games"
mkdir "Prologica\Magazines\Geracao Prologica (BR)"
mkdir "Raspberry Foundation\Raspberry Pi\Books"
mkdir "Sega\Books"
mkdir "Sega\Magazines\Sega Pro"
mkdir "Sega\Magazines\Sega Visions"
mkdir "Sega\Magazines\Supergame (BR)"
mkdir "Sega\Video"
mkdir "Sega\32X\Manuals\Games"
mkdir "Sega\32X\Manuals\Hardware"
mkdir "Sega\32X\Manuals\Technical"
mkdir "Sega\Computer 3000\Catalogs"
mkdir "Sega\Dreamcast\Commercials\Games"
mkdir "Sega\Dreamcast\Commercials\Hardware"
mkdir "Sega\Dreamcast\Magazines\DC-UK"
mkdir "Sega\Dreamcast\Magazines\Dreamcast Magazine"
mkdir "Sega\Dreamcast\Magazines\Dreamcast Monthly"
mkdir "Sega\Dreamcast\Magazines\Official Dreamcast Magazine, The (GB)"
mkdir "Sega\Dreamcast\Magazines\Official Dreamcast Magazine, The (US)"
mkdir "Sega\Dreamcast\Manuals\Games"
mkdir "Sega\Dreamcast\Manuals\Hardware"
mkdir "Sega\Game Gear\Manuals\Games"
mkdir "Sega\Game Gear\Manuals\Hardware"
mkdir "Sega\Mark III & Master System\Artwork\Games"
mkdir "Sega\Mark III & Master System\Books"
mkdir "Sega\Mark III & Master System\Catalogs"
mkdir "Sega\Mark III & Master System\Commercials\Hardware"
mkdir "Sega\Mark III & Master System\Manuals\Games"
mkdir "Sega\Mark III & Master System\Manuals\Hardware"
mkdir "Sega\Mega Drive & Genesis\Catalogs"
mkdir "Sega\Mega Drive & Genesis\Commercials\Hardware"
mkdir "Sega\Mega Drive & Genesis\Magazines\MegaTech"
mkdir "Sega\Mega Drive & Genesis\Magazines\Select Round (FR)"
mkdir "Sega\Mega Drive & Genesis\Manuals\Games"
mkdir "Sega\Mega Drive & Genesis\Manuals\Hardware"
mkdir "Sega\Mega Drive & Genesis\Manuals\Technical"
mkdir "Sega\Mega Drive & Genesis\Video"
mkdir "Sega\Mega-CD & Sega CD\Catalogs"
mkdir "Sega\Mega-CD & Sega CD\Commercials\Hardware"
mkdir "Sega\Mega-CD & Sega CD\Manuals\Games"
mkdir "Sega\Mega-CD & Sega CD\Manuals\Hardware"
mkdir "Sega\Mega-CD & Sega CD\Manuals\Multimedia"
mkdir "Sega\Pico\Artwork\Games"
mkdir "Sega\Pico\Manuals\Games"
mkdir "Sega\Saturn\Artwork\Games"
mkdir "Sega\Saturn\Catalogs"
mkdir "Sega\Saturn\Magazines\Saturn Plus"
mkdir "Sega\Saturn\Magazines\Saturn Power"
mkdir "Sega\Saturn\Magazines\Sega Saturn Magazine"
mkdir "Sega\Saturn\Manuals\Games"
mkdir "Sega\Saturn\Manuals\Hardware"
mkdir "Sinclair\ZX Spectrum\Books"
mkdir "Sinclair\ZX Spectrum\Magazines\Crash"
mkdir "Sinclair\ZX Spectrum\Magazines\Syntax ZX80"
mkdir "Sinclair\ZX Spectrum\Manuals\Hardware"
mkdir "Sinclair\ZX Spectrum\Manuals\Technical"
mkdir "SNK\Neo-Geo AES\Artwork\Games"
mkdir "SNK\Neo-Geo AES\Books"
mkdir "SNK\Neo-Geo AES\Catalogs"
mkdir "SNK\Neo-Geo AES\Magazines\Neo-Geo Freak (JP)"
mkdir "SNK\Neo-Geo AES\Magazines\Official Neo-Geo Newsletter, The"
mkdir "SNK\Neo-Geo AES\Manuals\Games"
mkdir "SNK\Neo-Geo AES\Manuals\Hardware"
mkdir "Sony\Books"
mkdir "Sony\Comics\Metal Gear Solid"
mkdir "Sony\PlayStation\Artwork\Games"
mkdir "Sony\PlayStation\Catalogs"
mkdir "Sony\PlayStation\Commercials\Games"
mkdir "Sony\PlayStation\Magazines\New Zealand Station"
mkdir "Sony\PlayStation\Magazines\Official NZ PlayStation Magazine"
mkdir "Sony\PlayStation\Magazines\Official PlayStation Magazine (RU)"
mkdir "Sony\PlayStation\Magazines\Official UK Playstation Magazine"
mkdir "Sony\PlayStation\Magazines\Official US PlayStation Magazine"
mkdir "Sony\PlayStation\Magazines\PlayStation Power"
mkdir "Sony\PlayStation\Magazines\Power"
mkdir "Sony\PlayStation\Magazines\PowerStation"
mkdir "Sony\PlayStation\Magazines\PSM"
mkdir "Sony\PlayStation\Manuals\Games"
mkdir "Sony\PlayStation 2\Artwork\Games"
mkdir "Sony\PlayStation 2\Books"
mkdir "Sony\PlayStation 2\Catalogs"
mkdir "Sony\PlayStation 2\Magazines\Play"
mkdir "Sony\PlayStation 2\Magazines\PlayStation 2"
mkdir "Sony\PlayStation 2\Magazines\PlayStation 2 Official Magazine (RU)"
mkdir "Sony\PlayStation 2\Magazines\PSM2"
mkdir "Sony\PlayStation 2\Manuals\Games"
mkdir "Sony\PlayStation 2\Video"
mkdir "Sony\PlayStation 3\Artwork\Games"
mkdir "Sony\PlayStation 3\Magazines\Official UK Playstation Magazine"
mkdir "Sony\PlayStation 3\Magazines\Official US Playstation Magazine"
mkdir "Sony\PlayStation 3\Magazines\Play"
mkdir "Sony\PlayStation 3\Magazines\Play Gamer"
mkdir "Sony\PlayStation 3\Magazines\PlayStation (RU)"
mkdir "Sony\PlayStation 3\Magazines\PSM3"
mkdir "Sony\PlayStation 3\Manuals\Games"
mkdir "Sony\PlayStation 4\Catalogs"
mkdir "Sony\PlayStation 4\Commercials\Games"
mkdir "Sony\PlayStation 4\Commercials\Hardware"
mkdir "Sony\PlayStation 4\Magazines\Playmania (ES)"
mkdir "Sony\PlayStation Portable\Artwork\Games"
mkdir "Sony\PlayStation Portable\Books"
mkdir "Sony\PlayStation Portable\Commercials\Games"
mkdir "Sony\PlayStation Portable\Magazines\PSP The Official Guide Book (RU)"
mkdir "Sony\PlayStation Portable\Manuals\Games"
mkdir "Tandy Radio Shack\Books"
mkdir "Tandy Radio Shack\Catalogs"
mkdir "Tandy Radio Shack\Comics\Tandy Computer Whiz Kids"
mkdir "Tandy Radio Shack\Commercials\Hardware"
mkdir "Tandy Radio Shack\Magazines\80 Micro"
mkdir "Tandy Radio Shack\Magazines\80 Notebook, The"
mkdir "Tandy Radio Shack\Magazines\80-Northwest (US)"
mkdir "Tandy Radio Shack\Magazines\80-US"
mkdir "Tandy Radio Shack\Magazines\Answers"
mkdir "Tandy Radio Shack\Magazines\Byte Bandits of America Tandy TRS-80's Computer Club Newsletter"
mkdir "Tandy Radio Shack\Magazines\CLOAD Magazine"
mkdir "Tandy Radio Shack\Magazines\DOSPLUS News Information Center"
mkdir "Tandy Radio Shack\Magazines\Gamers Connection!, The (US)"
mkdir "Tandy Radio Shack\Magazines\H & E Computronics"
mkdir "Tandy Radio Shack\Magazines\Kings Byte Newsletter"
mkdir "Tandy Radio Shack\Magazines\Northern Bytes"
mkdir "Tandy Radio Shack\Magazines\PROG-80"
mkdir "Tandy Radio Shack\Magazines\Rainbow, The (US)"
mkdir "Tandy Radio Shack\Magazines\S-EIGHTY, The"
mkdir "Tandy Radio Shack\Magazines\Softgold"
mkdir "Tandy Radio Shack\Magazines\TCS"
mkdir "Tandy Radio Shack\Magazines\Trace (FR)"
mkdir "Tandy Radio Shack\Magazines\TRS-80 Microcomputer News"
mkdir "Tandy Radio Shack\Magazines\TRS-80 Monthly Newsletter"
mkdir "Tandy Radio Shack\Magazines\TRS-80 Users Group Newsletter"
mkdir "Tandy Radio Shack\Magazines\TRSTimes"
mkdir "Tandy Radio Shack\Magazines\Various"
mkdir "Tandy Radio Shack\Manuals\Audio"
mkdir "Tandy Radio Shack\Manuals\Hardware"
mkdir "Tandy Radio Shack\Manuals\Software"
mkdir "Tandy Radio Shack\TRS-80 Color Computer\Books"
mkdir "Tandy Radio Shack\TRS-80 Color Computer\Magazines\CoCo-123"
mkdir "Tandy Radio Shack\TRS-80 Color Computer\Magazines\CoCoNutz! E-Zine"
mkdir "Tandy Radio Shack\TRS-80 Color Computer\Magazines\Color Micro Journal"
mkdir "Tandy Radio Shack\TRS-80 Color Computer\Magazines\Hardcopy (US)"
mkdir "Tandy Radio Shack\TRS-80 Color Computer\Manuals\Applications"
mkdir "Tandy Radio Shack\TRS-80 Color Computer\Manuals\Educational"
mkdir "Tandy Radio Shack\TRS-80 Color Computer\Manuals\Games"
mkdir "Tandy Radio Shack\TRS-80 Color Computer\Manuals\Hardware"
mkdir "Tangerine\Oric-1 & Oric Atmos\Books"
mkdir "Technosys\Aamber Pegasus\Magazines\Pegasus Newsletter (NZ)"
mkdir "Technosys\Aamber Pegasus\Manuals\Applications"
mkdir "Technosys\Aamber Pegasus\Manuals\Games"
mkdir "Technosys\Aamber Pegasus\Manuals\Hardware"
mkdir "Technosys\Aamber Pegasus\Manuals\Technical"
mkdir "Texas Instruments\Speak & Spell\Manuals\Games"
mkdir "Texas Instruments\TI-73\Manuals\Applications"
mkdir "Texas Instruments\TI-73\Manuals\Games"
mkdir "Texas Instruments\TI-99 4A\Books"
mkdir "Texas Instruments\TI-99 4A\Catalogs"
mkdir "Texas Instruments\TI-99 4A\Magazines\99er (US)"
mkdir "Texas Instruments\TI-99 4A\Manuals\Applications"
mkdir "Texas Instruments\TI-99 4A\Manuals\Games"
mkdir "Texas Instruments\TI-99 4A\Manuals\Hardware"
mkdir "University of Cambridge\EDSAC\Documentations\Software"
mkdir "VTech\Laser 200\Manuals\Hardware"
mkdir "VTech\V.Flash Home Edutainment System\Manuals\Games"
mkdir "VTech\V.Flash Home Edutainment System\Manuals\Hardware"
