mkdir "3DO\3DO Interactive Multiplayer\Applications\[IMG]"
mkdir "3DO\3DO Interactive Multiplayer\Applications\[ISO]"
mkdir "3DO\3DO Interactive Multiplayer\Bonus Discs"
mkdir "3DO\3DO Interactive Multiplayer\Coverdiscs\[IMG]"
mkdir "3DO\3DO Interactive Multiplayer\Coverdiscs\[ISO]"
mkdir "3DO\3DO Interactive Multiplayer\Educational\[IMG]"
mkdir "3DO\3DO Interactive Multiplayer\Educational\[ISO]"
mkdir "3DO\3DO Interactive Multiplayer\Firmware"
mkdir "3DO\3DO Interactive Multiplayer\Games"
mkdir "3DO\3DO Interactive Multiplayer\Homebrew\Applications"
mkdir "3DO\3DO Interactive Multiplayer\Homebrew\Compilations"
mkdir "3DO\3DO Interactive Multiplayer\Homebrew\Demos"
mkdir "3DO\3DO Interactive Multiplayer\Homebrew\Games"
mkdir "3DO\3DO Interactive Multiplayer\Multimedia"
mkdir "3DO\3DO Interactive Multiplayer\Samplers"
mkdir "Acorn\Archimedes\CD\Applications"
mkdir "Acorn\Archimedes\CD\Compilations"
mkdir "Acorn\Archimedes\CD\Coverdiscs"
mkdir "American Laser Games\CD-ROM System\Games"
mkdir "Apple\Macintosh\CD\Applications"
mkdir "Apple\Macintosh\CD\Coverdiscs"
mkdir "Apple\Macintosh\CD\Educational"
mkdir "Apple\Macintosh\CD\Games"
mkdir "Apple\Macintosh\CD\Multimedia"
mkdir "Atari\Jaguar CD\Bonus Discs"
mkdir "Atari\Jaguar CD\Games"
mkdir "Atari\Jaguar CD\Homebrew\Games\[BIN]"
mkdir "Atari\Jaguar CD\Homebrew\Games\[CDI]"
mkdir "Atari\Jaguar CD\Homebrew\Games\[NRG]"
mkdir "Atari\Jaguar CD\Samplers"
mkdir "Bandai\Pippin @World & Pippin Atmark\Applications"
mkdir "Bandai\Pippin @World & Pippin Atmark\Multimedia"
mkdir "Bandai\Playdia\Educational\[IMG]"
mkdir "Bandai\Playdia\Educational\[ISO]"
mkdir "Bandai\Playdia\Games\[IMG]"
mkdir "Bandai\Playdia\Games\[ISO]"
mkdir "Capcom\CP System III\Games"
mkdir "Commodore\Amiga\CD\Applications\[IMG]"
mkdir "Commodore\Amiga\CD\Applications\[ISO]"
mkdir "Commodore\Amiga\CD\Compilations\[BIN]"
mkdir "Commodore\Amiga\CD\Compilations\[IMG]"
mkdir "Commodore\Amiga\CD\Compilations\[ISO]"
mkdir "Commodore\Amiga\CD\Coverdiscs\[BIN]"
mkdir "Commodore\Amiga\CD\Coverdiscs\[ISO]"
mkdir "Commodore\Amiga\CD\Games\[BIN]"
mkdir "Commodore\Amiga\CD\Games\[IMG]"
mkdir "Commodore\Amiga\CD\Games\[ISO]"
mkdir "Commodore\Amiga\CD\Games\[MDF]"
mkdir "Commodore\Amiga\CD\Homebrew\[IMG]"
mkdir "Commodore\Amiga\CD\Multimedia\[IMG]"
mkdir "Commodore\Amiga\CD\Multimedia\[ISO]"
mkdir "Commodore\Amiga\CD\Operating Systems\[BIN]"
mkdir "Commodore\Amiga\CD\Operating Systems\[IMG]"
mkdir "Commodore\Amiga\CD\Operating Systems\[ISO]"
mkdir "Commodore\Amiga CD32\Applications"
mkdir "Commodore\Amiga CD32\Compilations\[IMG]"
mkdir "Commodore\Amiga CD32\Compilations\[ISO]"
mkdir "Commodore\Amiga CD32\Coverdiscs\[BIN]"
mkdir "Commodore\Amiga CD32\Coverdiscs\[IMG]"
mkdir "Commodore\Amiga CD32\Coverdiscs\[ISO]"
mkdir "Commodore\Amiga CD32\Demos"
mkdir "Commodore\Amiga CD32\Educational\[IMG]"
mkdir "Commodore\Amiga CD32\Educational\[ISO]"
mkdir "Commodore\Amiga CD32\Games\[BIN]"
mkdir "Commodore\Amiga CD32\Games\[IMG]"
mkdir "Commodore\Amiga CD32\Games\[ISO]"
mkdir "Commodore\Amiga CD32\Homebrew\Compilations\[BIN]"
mkdir "Commodore\Amiga CD32\Homebrew\Compilations\[IMG]"
mkdir "Commodore\Amiga CD32\Homebrew\Compilations\[ISO]"
mkdir "Commodore\Amiga CD32\Homebrew\Compilations\[Multipart]"
mkdir "Commodore\Amiga CD32\Homebrew\Compilations\[NRG]"
mkdir "Commodore\Amiga CD32\Homebrew\Games\[BIN]"
mkdir "Commodore\Amiga CD32\Homebrew\Games\[IMG]"
mkdir "Commodore\Amiga CD32\Homebrew\Games\[ISO]"
mkdir "Commodore\Amiga CD32\Homebrew\Games\[NRG]"
mkdir "Commodore\Amiga CD32\Homebrew\Multimedia"
mkdir "Commodore\Amiga CD32\Multimedia\[IMG]"
mkdir "Commodore\Amiga CD32\Multimedia\[ISO]"
mkdir "Commodore\Amiga CD32\Samplers"
mkdir "Commodore\Amiga CDTV\Applications\[IMG]"
mkdir "Commodore\Amiga CDTV\Applications\[ISO]"
mkdir "Commodore\Amiga CDTV\Compilations\[IMG]"
mkdir "Commodore\Amiga CDTV\Compilations\[ISO]"
mkdir "Commodore\Amiga CDTV\Educational\[IMG]"
mkdir "Commodore\Amiga CDTV\Educational\[ISO]"
mkdir "Commodore\Amiga CDTV\Entertainment"
mkdir "Commodore\Amiga CDTV\Games\[BIN]"
mkdir "Commodore\Amiga CDTV\Games\[IMG]"
mkdir "Commodore\Amiga CDTV\Games\[ISO]"
mkdir "Commodore\Amiga CDTV\Games\[MDF]"
mkdir "Commodore\Amiga CDTV\Homebrew\Compilations\[IMG]"
mkdir "Commodore\Amiga CDTV\Homebrew\Compilations\[ISO]"
mkdir "Commodore\Amiga CDTV\Homebrew\Games\[BIN]"
mkdir "Commodore\Amiga CDTV\Homebrew\Games\[ISO]"
mkdir "Commodore\Amiga CDTV\Multimedia\[IMG]"
mkdir "Commodore\Amiga CDTV\Multimedia\[ISO]"
mkdir "Commodore\Amiga CDTV\Samplers\[IMG]"
mkdir "Commodore\Amiga CDTV\Samplers\[ISO]"
mkdir "Commodore\C64\CD\Compilations\[ISO]"
mkdir "Fujitsu\FM Towns\CD\Applications"
mkdir "Fujitsu\FM Towns\CD\Compilations"
mkdir "Fujitsu\FM Towns\CD\Demos"
mkdir "Fujitsu\FM Towns\CD\Games"
mkdir "Fujitsu\FM Towns\CD\Homebrew\Demos"
mkdir "Fujitsu\FM Towns\CD\Homebrew\Games"
mkdir "Fujitsu\FM Towns\CD\Operating Systems"
mkdir "IBM\PC Compatibles\CD\Applications\[BIN-CUE]"
mkdir "IBM\PC Compatibles\CD\Applications\[ISO]"
mkdir "IBM\PC Compatibles\CD\Compilations"
mkdir "IBM\PC Compatibles\CD\Coverdiscs"
mkdir "IBM\PC Compatibles\CD\Educational"
mkdir "IBM\PC Compatibles\CD\Games"
mkdir "IBM\PC Compatibles\CD\Multimedia"
mkdir "IBM\PC Compatibles\CD\Operating Systems"
mkdir "IBM\PC Compatibles\CD\Samplers"
mkdir "Incredible Technologies\Eagle\CD\Games"
mkdir "Konami\Bemani System 573 Analog\Games"
mkdir "Konami\Bemani System 573 Digital\Games"
mkdir "Konami\System 573\Games"
mkdir "Mattel\HyperScan\Games"
mkdir "Memorex\Video Information System\Educational"
mkdir "Memorex\Video Information System\Games"
mkdir "Memorex\Video Information System\Multimedia"
mkdir "Memorex\Video Information System\Samplers"
mkdir "Namco-Sega-Nintendo\Triforce\Applications"
mkdir "Namco-Sega-Nintendo\Triforce\Games"
mkdir "NEC\PC-Engine CD & TurboGrafx-16 CD\Applications"
mkdir "NEC\PC-Engine CD & TurboGrafx-16 CD\Compilations"
mkdir "NEC\PC-Engine CD & TurboGrafx-16 CD\Educational"
mkdir "NEC\PC-Engine CD & TurboGrafx-16 CD\Games\[BIN]"
mkdir "NEC\PC-Engine CD & TurboGrafx-16 CD\Games\[IMG]"
mkdir "NEC\PC-Engine CD & TurboGrafx-16 CD\Games\[ISO]"
mkdir "NEC\PC-Engine CD & TurboGrafx-16 CD\Homebrew\Games"
mkdir "NEC\PC-Engine CD & TurboGrafx-16 CD\Multimedia"
mkdir "NEC\PC-Engine CD & TurboGrafx-16 CD\Samplers\[BIN]"
mkdir "NEC\PC-Engine CD & TurboGrafx-16 CD\Samplers\[IMG]"
mkdir "NEC\PC-FX\Firmware"
mkdir "NEC\PC-FX\Games"
mkdir "NEC\PC-FXGA\Firmware"
mkdir "NEC\PC-FXGA\Games"
mkdir "Nintendo\GameCube\Applications"
mkdir "Nintendo\GameCube\Games"
mkdir "Nintendo\GameCube\Samplers"
mkdir "Nintendo\Super Famicom & Super Entertainment System\Voicer-kun Audio CDs"
mkdir "Philips\CD-i\Applications"
mkdir "Philips\CD-i\Bonus Discs"
mkdir "Philips\CD-i\Coverdiscs"
mkdir "Philips\CD-i\Educational"
mkdir "Philips\CD-i\Firmware"
mkdir "Philips\CD-i\Games"
mkdir "Philips\CD-i\Homebrew\Demos"
mkdir "Philips\CD-i\Homebrew\Games\[BIN]"
mkdir "Philips\CD-i\Homebrew\Games\[NRG]"
mkdir "Philips\CD-i\Multimedia"
mkdir "Philips\CD-i\Samplers"
mkdir "Sega\32X\CD\Games\[BIN-CUE]"
mkdir "Sega\32X\CD\Games\[IMG]"
mkdir "Sega\32X\CD\Games\[ISO]"
mkdir "Sega\Chihiro\Games"
mkdir "Sega\Dreamcast\Applications"
mkdir "Sega\Dreamcast\Firmware"
mkdir "Sega\Dreamcast\Games\Dev Builds\[BIN]"
mkdir "Sega\Dreamcast\Games\Dev Builds\[ISO]"
mkdir "Sega\Dreamcast\Games\JP"
mkdir "Sega\Dreamcast\Games\PAL"
mkdir "Sega\Dreamcast\Games\US"
mkdir "Sega\Dreamcast\Homebrew\Applications\[CDI]"
mkdir "Sega\Dreamcast\Homebrew\Compilations\[CDI]"
mkdir "Sega\Dreamcast\Homebrew\Demos\[BIN]"
mkdir "Sega\Dreamcast\Homebrew\Demos\[CDI]"
mkdir "Sega\Dreamcast\Homebrew\Demos\[ELF]"
mkdir "Sega\Dreamcast\Homebrew\Demos\[Multipart]"
mkdir "Sega\Dreamcast\Homebrew\Demos\[NRG]"
mkdir "Sega\Dreamcast\Homebrew\Games\[CDI]"
mkdir "Sega\Dreamcast\Homebrew\Games\[GDI]"
mkdir "Sega\Dreamcast\Homebrew\Games\[MDF-MDS]"
mkdir "Sega\Dreamcast\Multimedia"
mkdir "Sega\Dreamcast\Samplers"
mkdir "Sega\Dreamcast\Various Unverified Dumps"
mkdir "Sega\Mega-CD & Sega CD\CD\Applications"
mkdir "Sega\Mega-CD & Sega CD\CD\Bonus Discs\[IMG]"
mkdir "Sega\Mega-CD & Sega CD\CD\Bonus Discs\[ISO]"
mkdir "Sega\Mega-CD & Sega CD\CD\Educational\[IMG]"
mkdir "Sega\Mega-CD & Sega CD\CD\Educational\[ISO]"
mkdir "Sega\Mega-CD & Sega CD\CD\Games\[IMG]"
mkdir "Sega\Mega-CD & Sega CD\CD\Games\[ISO]"
mkdir "Sega\Mega-CD & Sega CD\CD\Multimedia\[IMG]"
mkdir "Sega\Mega-CD & Sega CD\CD\Multimedia\[ISO]"
mkdir "Sega\Mega-CD & Sega CD\CD\Samplers\[IMG]"
mkdir "Sega\Mega-CD & Sega CD\CD\Samplers\[ISO]"
mkdir "Sega\Mega-CD & Sega CD\Homebrew\Demos"
mkdir "Sega\Mega-CD & Sega CD\Homebrew\Games"
mkdir "Sega\NAOMI\Applications"
mkdir "Sega\NAOMI\Games"
mkdir "Sega\NAOMI 2\Games"
mkdir "Sega\Saturn\Applications"
mkdir "Sega\Saturn\Bonus Discs"
mkdir "Sega\Saturn\Firmware"
mkdir "Sega\Saturn\Games\[BIN]"
mkdir "Sega\Saturn\Games\[ISO]"
mkdir "Sega\Saturn\Homebrew\Games\[ISO]"
mkdir "Sega\Saturn\Multimedia"
mkdir "Sega\Saturn\Samplers"
mkdir "Sega\WonderMega\CD\Educational\[IMG]"
mkdir "Sega\WonderMega\CD\Educational\[ISO]"
mkdir "Sega\WonderMega\CD\Games"
mkdir "Sega\WonderMega\CD\Samplers"
mkdir "Sinclair\ZX Spectrum\CD\Compilations"
mkdir "SNK\Hyper Neo-Geo 64\CD\Multimedia"
mkdir "SNK\Neo-Geo CD\Bonus Discs"
mkdir "SNK\Neo-Geo CD\Demos"
mkdir "SNK\Neo-Geo CD\Firmware"
mkdir "SNK\Neo-Geo CD\Games\[IMG]"
mkdir "SNK\Neo-Geo CD\Games\[ISO]"
mkdir "SNK\Neo-Geo CD\Games\[Multipart]"
mkdir "SNK\Neo-Geo CD\Multimedia\[IMG]"
mkdir "SNK\Neo-Geo CD\Multimedia\[ISO]"
mkdir "SNK\Neo-Geo CD\Samplers\[IMG]"
mkdir "SNK\Neo-Geo CD\Samplers\[ISO]"
mkdir "SNK\Neo-Geo CD\Samplers\[Multipart]"
mkdir "Sony\PlayStation\Applications"
mkdir "Sony\PlayStation\Coverdiscs"
mkdir "Sony\PlayStation\Demos\[BIN]"
mkdir "Sony\PlayStation\Demos\[EXE]"
mkdir "Sony\PlayStation\Demos\[ISO]"
mkdir "Sony\PlayStation\Demos\[Multipart]"
mkdir "Sony\PlayStation\Demos\[PSX]"
mkdir "Sony\PlayStation\Firmware"
mkdir "Sony\PlayStation\Games\[BIN]"
mkdir "Sony\PlayStation\Games\[EXE]"
mkdir "Sony\PlayStation\Games\[IMG]"
mkdir "Sony\PlayStation\Games\[ISO]"
mkdir "Sony\PlayStation\Homebrew\Games\[BIN]"
mkdir "Sony\PlayStation\Homebrew\Games\[ISO]"
mkdir "Sony\PlayStation\Samplers\[BIN]"
mkdir "Sony\PlayStation\Samplers\[ISO]"
mkdir "Sony\PlayStation 2\Coverdiscs\[ISO]"
mkdir "Sony\PlayStation 2\Firmware"
mkdir "Sony\PlayStation 2\Games\[ISO]"
mkdir "Sony\PlayStation 2\Homebrew\Games\[ISO]"
mkdir "Sony\PlayStation 2\Samplers\[ISO]"
mkdir "Sony\PlayStation Portable\Applications\[ISO]"
mkdir "Sony\PlayStation Portable\Games\[ISO]"
mkdir "Sony\PlayStation Portable\Homebrew\Games\[ISO]"
mkdir "Sony\PlayStation Portable\Samplers\[ISO]"
mkdir "Tomy\KISS-Site\Games"
mkdir "VM Labs\Nuon\Games"
mkdir "VTech\V.Flash Home Edutainment System\Educational"
mkdir "ZAPiT Games\Game Wave Family Entertainment System\Games"
