move "3DO 3DO Interactive Multiplayer - Applications - [IMG] (TOSEC-v2017-09-15_CM).dat" "3DO\3DO Interactive Multiplayer\Applications\[IMG]"
move "3DO 3DO Interactive Multiplayer - Applications - [ISO] (TOSEC-v2012-07-05_CM).dat" "3DO\3DO Interactive Multiplayer\Applications\[ISO]"
move "3DO 3DO Interactive Multiplayer - Bonus Discs (TOSEC-v2012-07-05_CM).dat" "3DO\3DO Interactive Multiplayer\Bonus Discs"
move "3DO 3DO Interactive Multiplayer - Coverdiscs - [IMG] (TOSEC-v2017-09-17_CM).dat" "3DO\3DO Interactive Multiplayer\Coverdiscs\[IMG]"
move "3DO 3DO Interactive Multiplayer - Coverdiscs - [ISO] (TOSEC-v2012-07-05_CM).dat" "3DO\3DO Interactive Multiplayer\Coverdiscs\[ISO]"
move "3DO 3DO Interactive Multiplayer - Educational - [IMG] (TOSEC-v2017-09-29_CM).dat" "3DO\3DO Interactive Multiplayer\Educational\[IMG]"
move "3DO 3DO Interactive Multiplayer - Educational - [ISO] (TOSEC-v2020-11-18_CM).dat" "3DO\3DO Interactive Multiplayer\Educational\[ISO]"
move "3DO 3DO Interactive Multiplayer - Firmware (TOSEC-v2017-07-07_CM).dat" "3DO\3DO Interactive Multiplayer\Firmware"
move "3DO 3DO Interactive Multiplayer - Games (TOSEC-v2020-11-20_CM).dat" "3DO\3DO Interactive Multiplayer\Games"
move "3DO 3DO Interactive Multiplayer - Homebrew - Applications (TOSEC-v2017-09-15_CM).dat" "3DO\3DO Interactive Multiplayer\Homebrew\Applications"
move "3DO 3DO Interactive Multiplayer - Homebrew - Compilations (TOSEC-v2022-06-08_CM).dat" "3DO\3DO Interactive Multiplayer\Homebrew\Compilations"
move "3DO 3DO Interactive Multiplayer - Homebrew - Demos (TOSEC-v2020-07-14_CM).dat" "3DO\3DO Interactive Multiplayer\Homebrew\Demos"
move "3DO 3DO Interactive Multiplayer - Homebrew - Games (TOSEC-v2022-06-08_CM).dat" "3DO\3DO Interactive Multiplayer\Homebrew\Games"
move "3DO 3DO Interactive Multiplayer - Multimedia (TOSEC-v2012-07-05_CM).dat" "3DO\3DO Interactive Multiplayer\Multimedia"
move "3DO 3DO Interactive Multiplayer - Samplers (TOSEC-v2023-01-08_CM).dat" "3DO\3DO Interactive Multiplayer\Samplers"
move "Acorn Archimedes - CD - Applications (TOSEC-v2012-07-06_CM).dat" "Acorn\Archimedes\CD\Applications"
move "Acorn Archimedes - CD - Compilations (TOSEC-v2012-07-06_CM).dat" "Acorn\Archimedes\CD\Compilations"
move "Acorn Archimedes - CD - Coverdiscs (TOSEC-v2012-07-06_CM).dat" "Acorn\Archimedes\CD\Coverdiscs"
move "American Laser Games CD-ROM System - Games (TOSEC-v2012-07-05_CM).dat" "American Laser Games\CD-ROM System\Games"
move "Apple Macintosh - CD - Applications (TOSEC-v2012-07-06_CM).dat" "Apple\Macintosh\CD\Applications"
move "Apple Macintosh - CD - Coverdiscs (TOSEC-v2012-07-06_CM).dat" "Apple\Macintosh\CD\Coverdiscs"
move "Apple Macintosh - CD - Educational (TOSEC-v2012-07-06_CM).dat" "Apple\Macintosh\CD\Educational"
move "Apple Macintosh - CD - Games (TOSEC-v2012-07-06_CM).dat" "Apple\Macintosh\CD\Games"
move "Apple Macintosh - CD - Multimedia (TOSEC-v2012-07-06_CM).dat" "Apple\Macintosh\CD\Multimedia"
move "Atari Jaguar CD - Bonus Discs (TOSEC-v2012-07-17_CM).dat" "Atari\Jaguar CD\Bonus Discs"
move "Atari Jaguar CD - Games (TOSEC-v2012-07-17_CM).dat" "Atari\Jaguar CD\Games"
move "Atari Jaguar CD - Homebrew - Games - [BIN] (TOSEC-v2012-07-22_CM).dat" "Atari\Jaguar CD\Homebrew\Games\[BIN]"
move "Atari Jaguar CD - Homebrew - Games - [CDI] (TOSEC-v2022-06-08_CM).dat" "Atari\Jaguar CD\Homebrew\Games\[CDI]"
move "Atari Jaguar CD - Homebrew - Games - [NRG] (TOSEC-v2012-07-22_CM).dat" "Atari\Jaguar CD\Homebrew\Games\[NRG]"
move "Atari Jaguar CD - Samplers (TOSEC-v2012-07-17_CM).dat" "Atari\Jaguar CD\Samplers"
move "Bandai Pippin @World & Pippin Atmark - Applications (TOSEC-v2012-07-06_CM).dat" "Bandai\Pippin @World & Pippin Atmark\Applications"
move "Bandai Pippin @World & Pippin Atmark - Multimedia (TOSEC-v2012-07-06_CM).dat" "Bandai\Pippin @World & Pippin Atmark\Multimedia"
move "Bandai Playdia - Educational - [IMG] (TOSEC-v2013-04-10_CM).dat" "Bandai\Playdia\Educational\[IMG]"
move "Bandai Playdia - Educational - [ISO] (TOSEC-v2013-10-18_CM).dat" "Bandai\Playdia\Educational\[ISO]"
move "Bandai Playdia - Games - [IMG] (TOSEC-v2013-04-10_CM).dat" "Bandai\Playdia\Games\[IMG]"
move "Bandai Playdia - Games - [ISO] (TOSEC-v2013-10-18_CM).dat" "Bandai\Playdia\Games\[ISO]"
move "Capcom CP System III - Games (TOSEC-v2012-07-22_CM).dat" "Capcom\CP System III\Games"
move "Commodore Amiga - CD - Applications - [IMG] (TOSEC-v2018-07-02_CM).dat" "Commodore\Amiga\CD\Applications\[IMG]"
move "Commodore Amiga - CD - Applications - [ISO] (TOSEC-v2019-09-07_CM).dat" "Commodore\Amiga\CD\Applications\[ISO]"
move "Commodore Amiga - CD - Compilations - [BIN] (TOSEC-v2018-07-02_CM).dat" "Commodore\Amiga\CD\Compilations\[BIN]"
move "Commodore Amiga - CD - Compilations - [IMG] (TOSEC-v2018-07-02_CM).dat" "Commodore\Amiga\CD\Compilations\[IMG]"
move "Commodore Amiga - CD - Compilations - [ISO] (TOSEC-v2019-09-07_CM).dat" "Commodore\Amiga\CD\Compilations\[ISO]"
move "Commodore Amiga - CD - Coverdiscs - [BIN] (TOSEC-v2017-10-23_CM).dat" "Commodore\Amiga\CD\Coverdiscs\[BIN]"
move "Commodore Amiga - CD - Coverdiscs - [ISO] (TOSEC-v2021-02-12_CM).dat" "Commodore\Amiga\CD\Coverdiscs\[ISO]"
move "Commodore Amiga - CD - Games - [BIN] (TOSEC-v2018-07-02_CM).dat" "Commodore\Amiga\CD\Games\[BIN]"
move "Commodore Amiga - CD - Games - [IMG] (TOSEC-v2019-12-21_CM).dat" "Commodore\Amiga\CD\Games\[IMG]"
move "Commodore Amiga - CD - Games - [ISO] (TOSEC-v2019-09-07_CM).dat" "Commodore\Amiga\CD\Games\[ISO]"
move "Commodore Amiga - CD - Games - [MDF] (TOSEC-v2018-07-03_CM).dat" "Commodore\Amiga\CD\Games\[MDF]"
move "Commodore Amiga - CD - Homebrew - [IMG] (TOSEC-v2018-07-02_CM).dat" "Commodore\Amiga\CD\Homebrew\[IMG]"
move "Commodore Amiga - CD - Multimedia - [IMG] (TOSEC-v2018-07-02_CM).dat" "Commodore\Amiga\CD\Multimedia\[IMG]"
move "Commodore Amiga - CD - Multimedia - [ISO] (TOSEC-v2018-07-02_CM).dat" "Commodore\Amiga\CD\Multimedia\[ISO]"
move "Commodore Amiga - CD - Operating Systems - [BIN] (TOSEC-v2019-09-07_CM).dat" "Commodore\Amiga\CD\Operating Systems\[BIN]"
move "Commodore Amiga - CD - Operating Systems - [IMG] (TOSEC-v2019-09-07_CM).dat" "Commodore\Amiga\CD\Operating Systems\[IMG]"
move "Commodore Amiga - CD - Operating Systems - [ISO] (TOSEC-v2019-09-07_CM).dat" "Commodore\Amiga\CD\Operating Systems\[ISO]"
move "Commodore Amiga CD32 - Applications (TOSEC-v2018-03-24_CM).dat" "Commodore\Amiga CD32\Applications"
move "Commodore Amiga CD32 - Compilations - [IMG] (TOSEC-v2019-09-07_CM).dat" "Commodore\Amiga CD32\Compilations\[IMG]"
move "Commodore Amiga CD32 - Compilations - [ISO] (TOSEC-v2019-09-07_CM).dat" "Commodore\Amiga CD32\Compilations\[ISO]"
move "Commodore Amiga CD32 - Coverdiscs - [BIN] (TOSEC-v2018-03-24_CM).dat" "Commodore\Amiga CD32\Coverdiscs\[BIN]"
move "Commodore Amiga CD32 - Coverdiscs - [IMG] (TOSEC-v2019-09-07_CM).dat" "Commodore\Amiga CD32\Coverdiscs\[IMG]"
move "Commodore Amiga CD32 - Coverdiscs - [ISO] (TOSEC-v2018-03-25_CM).dat" "Commodore\Amiga CD32\Coverdiscs\[ISO]"
move "Commodore Amiga CD32 - Demos (TOSEC-v2017-10-23_CM).dat" "Commodore\Amiga CD32\Demos"
move "Commodore Amiga CD32 - Educational - [IMG] (TOSEC-v2018-03-24_CM).dat" "Commodore\Amiga CD32\Educational\[IMG]"
move "Commodore Amiga CD32 - Educational - [ISO] (TOSEC-v2018-03-25_CM).dat" "Commodore\Amiga CD32\Educational\[ISO]"
move "Commodore Amiga CD32 - Games - [BIN] (TOSEC-v2019-09-07_CM).dat" "Commodore\Amiga CD32\Games\[BIN]"
move "Commodore Amiga CD32 - Games - [IMG] (TOSEC-v2019-12-21_CM).dat" "Commodore\Amiga CD32\Games\[IMG]"
move "Commodore Amiga CD32 - Games - [ISO] (TOSEC-v2018-03-24_CM).dat" "Commodore\Amiga CD32\Games\[ISO]"
move "Commodore Amiga CD32 - Homebrew - Compilations - [BIN] (TOSEC-v2018-03-24_CM).dat" "Commodore\Amiga CD32\Homebrew\Compilations\[BIN]"
move "Commodore Amiga CD32 - Homebrew - Compilations - [IMG] (TOSEC-v2018-07-02_CM).dat" "Commodore\Amiga CD32\Homebrew\Compilations\[IMG]"
move "Commodore Amiga CD32 - Homebrew - Compilations - [ISO] (TOSEC-v2018-07-02_CM).dat" "Commodore\Amiga CD32\Homebrew\Compilations\[ISO]"
move "Commodore Amiga CD32 - Homebrew - Compilations - [Multipart] (TOSEC-v2012-07-22_CM).dat" "Commodore\Amiga CD32\Homebrew\Compilations\[Multipart]"
move "Commodore Amiga CD32 - Homebrew - Compilations - [NRG] (TOSEC-v2012-07-22_CM).dat" "Commodore\Amiga CD32\Homebrew\Compilations\[NRG]"
move "Commodore Amiga CD32 - Homebrew - Games - [BIN] (TOSEC-v2012-07-22_CM).dat" "Commodore\Amiga CD32\Homebrew\Games\[BIN]"
move "Commodore Amiga CD32 - Homebrew - Games - [IMG] (TOSEC-v2012-07-22_CM).dat" "Commodore\Amiga CD32\Homebrew\Games\[IMG]"
move "Commodore Amiga CD32 - Homebrew - Games - [ISO] (TOSEC-v2020-10-30_CM).dat" "Commodore\Amiga CD32\Homebrew\Games\[ISO]"
move "Commodore Amiga CD32 - Homebrew - Games - [NRG] (TOSEC-v2014-10-28_CM).dat" "Commodore\Amiga CD32\Homebrew\Games\[NRG]"
move "Commodore Amiga CD32 - Homebrew - Multimedia (TOSEC-v2012-07-22_CM).dat" "Commodore\Amiga CD32\Homebrew\Multimedia"
move "Commodore Amiga CD32 - Multimedia - [IMG] (TOSEC-v2019-09-07_CM).dat" "Commodore\Amiga CD32\Multimedia\[IMG]"
move "Commodore Amiga CD32 - Multimedia - [ISO] (TOSEC-v2018-03-25_CM).dat" "Commodore\Amiga CD32\Multimedia\[ISO]"
move "Commodore Amiga CD32 - Samplers (TOSEC-v2012-07-13_CM).dat" "Commodore\Amiga CD32\Samplers"
move "Commodore Amiga CDTV - Applications - [IMG] (TOSEC-v2018-03-24_CM).dat" "Commodore\Amiga CDTV\Applications\[IMG]"
move "Commodore Amiga CDTV - Applications - [ISO] (TOSEC-v2018-03-24_CM).dat" "Commodore\Amiga CDTV\Applications\[ISO]"
move "Commodore Amiga CDTV - Compilations - [IMG] (TOSEC-v2018-03-24_CM).dat" "Commodore\Amiga CDTV\Compilations\[IMG]"
move "Commodore Amiga CDTV - Compilations - [ISO] (TOSEC-v2018-03-25_CM).dat" "Commodore\Amiga CDTV\Compilations\[ISO]"
move "Commodore Amiga CDTV - Educational - [IMG] (TOSEC-v2018-03-24_CM).dat" "Commodore\Amiga CDTV\Educational\[IMG]"
move "Commodore Amiga CDTV - Educational - [ISO] (TOSEC-v2018-03-24_CM).dat" "Commodore\Amiga CDTV\Educational\[ISO]"
move "Commodore Amiga CDTV - Entertainment (TOSEC-v2016-07-02_CM).dat" "Commodore\Amiga CDTV\Entertainment"
move "Commodore Amiga CDTV - Games - [BIN] (TOSEC-v2018-03-24_CM).dat" "Commodore\Amiga CDTV\Games\[BIN]"
move "Commodore Amiga CDTV - Games - [IMG] (TOSEC-v2018-03-25_CM).dat" "Commodore\Amiga CDTV\Games\[IMG]"
move "Commodore Amiga CDTV - Games - [ISO] (TOSEC-v2018-03-24_CM).dat" "Commodore\Amiga CDTV\Games\[ISO]"
move "Commodore Amiga CDTV - Games - [MDF] (TOSEC-v2018-03-24_CM).dat" "Commodore\Amiga CDTV\Games\[MDF]"
move "Commodore Amiga CDTV - Homebrew - Compilations - [IMG] (TOSEC-v2012-07-22_CM).dat" "Commodore\Amiga CDTV\Homebrew\Compilations\[IMG]"
move "Commodore Amiga CDTV - Homebrew - Compilations - [ISO] (TOSEC-v2012-07-22_CM).dat" "Commodore\Amiga CDTV\Homebrew\Compilations\[ISO]"
move "Commodore Amiga CDTV - Homebrew - Games - [BIN] (TOSEC-v2012-07-22_CM).dat" "Commodore\Amiga CDTV\Homebrew\Games\[BIN]"
move "Commodore Amiga CDTV - Homebrew - Games - [ISO] (TOSEC-v2018-03-25_CM).dat" "Commodore\Amiga CDTV\Homebrew\Games\[ISO]"
move "Commodore Amiga CDTV - Multimedia - [IMG] (TOSEC-v2018-03-25_CM).dat" "Commodore\Amiga CDTV\Multimedia\[IMG]"
move "Commodore Amiga CDTV - Multimedia - [ISO] (TOSEC-v2018-03-25_CM).dat" "Commodore\Amiga CDTV\Multimedia\[ISO]"
move "Commodore Amiga CDTV - Samplers - [IMG] (TOSEC-v2018-03-24_CM).dat" "Commodore\Amiga CDTV\Samplers\[IMG]"
move "Commodore Amiga CDTV - Samplers - [ISO] (TOSEC-v2018-03-24_CM).dat" "Commodore\Amiga CDTV\Samplers\[ISO]"
move "Commodore C64 - CD - Compilations - [ISO] (TOSEC-v2018-07-02_CM).dat" "Commodore\C64\CD\Compilations\[ISO]"
move "Fujitsu FM Towns - CD - Applications (TOSEC-v2021-12-11_CM).dat" "Fujitsu\FM Towns\CD\Applications"
move "Fujitsu FM Towns - CD - Compilations (TOSEC-v2012-07-13_CM).dat" "Fujitsu\FM Towns\CD\Compilations"
move "Fujitsu FM Towns - CD - Demos (TOSEC-v2021-12-11_CM).dat" "Fujitsu\FM Towns\CD\Demos"
move "Fujitsu FM Towns - CD - Games (TOSEC-v2012-07-13_CM).dat" "Fujitsu\FM Towns\CD\Games"
move "Fujitsu FM Towns - CD - Homebrew - Demos (TOSEC-v2012-07-22_CM).dat" "Fujitsu\FM Towns\CD\Homebrew\Demos"
move "Fujitsu FM Towns - CD - Homebrew - Games (TOSEC-v2012-07-22_CM).dat" "Fujitsu\FM Towns\CD\Homebrew\Games"
move "Fujitsu FM Towns - CD - Operating Systems (TOSEC-v2021-12-11_CM).dat" "Fujitsu\FM Towns\CD\Operating Systems"
move "IBM PC Compatibles - CD - Applications - [BIN-CUE] (TOSEC-v2022-06-08_CM).dat" "IBM\PC Compatibles\CD\Applications\[BIN-CUE]"
move "IBM PC Compatibles - CD - Applications - [ISO] (TOSEC-v2022-06-08_CM).dat" "IBM\PC Compatibles\CD\Applications\[ISO]"
move "IBM PC Compatibles - CD - Compilations (TOSEC-v2012-07-13_CM).dat" "IBM\PC Compatibles\CD\Compilations"
move "IBM PC Compatibles - CD - Coverdiscs (TOSEC-v2012-07-13_CM).dat" "IBM\PC Compatibles\CD\Coverdiscs"
move "IBM PC Compatibles - CD - Educational (TOSEC-v2012-07-13_CM).dat" "IBM\PC Compatibles\CD\Educational"
move "IBM PC Compatibles - CD - Games (TOSEC-v2022-06-08_CM).dat" "IBM\PC Compatibles\CD\Games"
move "IBM PC Compatibles - CD - Multimedia (TOSEC-v2012-07-13_CM).dat" "IBM\PC Compatibles\CD\Multimedia"
move "IBM PC Compatibles - CD - Operating Systems (TOSEC-v2012-07-13_CM).dat" "IBM\PC Compatibles\CD\Operating Systems"
move "IBM PC Compatibles - CD - Samplers (TOSEC-v2012-07-13_CM).dat" "IBM\PC Compatibles\CD\Samplers"
move "Incredible Technologies Eagle - CD - Games (TOSEC-v2012-07-22_CM).dat" "Incredible Technologies\Eagle\CD\Games"
move "Konami Bemani System 573 Analog - Games (TOSEC-v2012-07-22_CM).dat" "Konami\Bemani System 573 Analog\Games"
move "Konami Bemani System 573 Digital - Games (TOSEC-v2012-07-22_CM).dat" "Konami\Bemani System 573 Digital\Games"
move "Konami System 573 - Games (TOSEC-v2012-07-22_CM).dat" "Konami\System 573\Games"
move "Mattel HyperScan - Games (TOSEC-v2019-04-18_CM).dat" "Mattel\HyperScan\Games"
move "Memorex Video Information System - Educational (TOSEC-v2012-07-13_CM).dat" "Memorex\Video Information System\Educational"
move "Memorex Video Information System - Games (TOSEC-v2012-07-13_CM).dat" "Memorex\Video Information System\Games"
move "Memorex Video Information System - Multimedia (TOSEC-v2012-07-13_CM).dat" "Memorex\Video Information System\Multimedia"
move "Memorex Video Information System - Samplers (TOSEC-v2012-07-13_CM).dat" "Memorex\Video Information System\Samplers"
move "Namco-Sega-Nintendo Triforce - Applications (TOSEC-v2022-12-20_CM).dat" "Namco-Sega-Nintendo\Triforce\Applications"
move "Namco-Sega-Nintendo Triforce - Games (TOSEC-v2022-12-20_CM).dat" "Namco-Sega-Nintendo\Triforce\Games"
move "NEC PC-Engine CD & TurboGrafx-16 CD - Applications (TOSEC-v2018-03-23_CM).dat" "NEC\PC-Engine CD & TurboGrafx-16 CD\Applications"
move "NEC PC-Engine CD & TurboGrafx-16 CD - Compilations (TOSEC-v2019-04-18_CM).dat" "NEC\PC-Engine CD & TurboGrafx-16 CD\Compilations"
move "NEC PC-Engine CD & TurboGrafx-16 CD - Educational (TOSEC-v2018-05-28_CM).dat" "NEC\PC-Engine CD & TurboGrafx-16 CD\Educational"
move "NEC PC-Engine CD & TurboGrafx-16 CD - Games - [BIN] (TOSEC-v2018-08-10_CM).dat" "NEC\PC-Engine CD & TurboGrafx-16 CD\Games\[BIN]"
move "NEC PC-Engine CD & TurboGrafx-16 CD - Games - [IMG] (TOSEC-v2021-05-07_CM).dat" "NEC\PC-Engine CD & TurboGrafx-16 CD\Games\[IMG]"
move "NEC PC-Engine CD & TurboGrafx-16 CD - Games - [ISO] (TOSEC-v2018-08-10_CM).dat" "NEC\PC-Engine CD & TurboGrafx-16 CD\Games\[ISO]"
move "NEC PC-Engine CD & TurboGrafx-16 CD - Homebrew - Games (TOSEC-v2012-07-22_CM).dat" "NEC\PC-Engine CD & TurboGrafx-16 CD\Homebrew\Games"
move "NEC PC-Engine CD & TurboGrafx-16 CD - Multimedia (TOSEC-v2018-06-07_CM).dat" "NEC\PC-Engine CD & TurboGrafx-16 CD\Multimedia"
move "NEC PC-Engine CD & TurboGrafx-16 CD - Samplers - [BIN] (TOSEC-v2018-07-20_CM).dat" "NEC\PC-Engine CD & TurboGrafx-16 CD\Samplers\[BIN]"
move "NEC PC-Engine CD & TurboGrafx-16 CD - Samplers - [IMG] (TOSEC-v2019-04-18_CM).dat" "NEC\PC-Engine CD & TurboGrafx-16 CD\Samplers\[IMG]"
move "NEC PC-FX - Firmware (TOSEC-v2012-07-13_CM).dat" "NEC\PC-FX\Firmware"
move "NEC PC-FX - Games (TOSEC-v2012-07-14_CM).dat" "NEC\PC-FX\Games"
move "NEC PC-FXGA - Firmware (TOSEC-v2012-07-13_CM).dat" "NEC\PC-FXGA\Firmware"
move "NEC PC-FXGA - Games (TOSEC-v2012-07-13_CM).dat" "NEC\PC-FXGA\Games"
move "Nintendo GameCube - Applications (TOSEC-v2022-08-25_CM).dat" "Nintendo\GameCube\Applications"
move "Nintendo GameCube - Games (TOSEC-v2022-12-27_CM).dat" "Nintendo\GameCube\Games"
move "Nintendo GameCube - Samplers (TOSEC-v2022-12-22_CM).dat" "Nintendo\GameCube\Samplers"
move "Nintendo Super Famicom & Super Entertainment System - Voicer-kun Audio CDs (TOSEC-v2022-06-23_CM).dat" "Nintendo\Super Famicom & Super Entertainment System\Voicer-kun Audio CDs"
move "Philips CD-i - Applications (TOSEC-v2012-07-13_CM).dat" "Philips\CD-i\Applications"
move "Philips CD-i - Bonus Discs (TOSEC-v2012-07-13_CM).dat" "Philips\CD-i\Bonus Discs"
move "Philips CD-i - Coverdiscs (TOSEC-v2012-07-13_CM).dat" "Philips\CD-i\Coverdiscs"
move "Philips CD-i - Educational (TOSEC-v2012-07-13_CM).dat" "Philips\CD-i\Educational"
move "Philips CD-i - Firmware (TOSEC-v2012-07-13_CM).dat" "Philips\CD-i\Firmware"
move "Philips CD-i - Games (TOSEC-v2012-07-13_CM).dat" "Philips\CD-i\Games"
move "Philips CD-i - Homebrew - Demos (TOSEC-v2012-07-22_CM).dat" "Philips\CD-i\Homebrew\Demos"
move "Philips CD-i - Homebrew - Games - [BIN] (TOSEC-v2012-07-22_CM).dat" "Philips\CD-i\Homebrew\Games\[BIN]"
move "Philips CD-i - Homebrew - Games - [NRG] (TOSEC-v2012-07-22_CM).dat" "Philips\CD-i\Homebrew\Games\[NRG]"
move "Philips CD-i - Multimedia (TOSEC-v2013-10-03_CM).dat" "Philips\CD-i\Multimedia"
move "Philips CD-i - Samplers (TOSEC-v2012-07-13_CM).dat" "Philips\CD-i\Samplers"
move "Sega 32X - CD - Games - [BIN-CUE] (TOSEC-v2022-06-08_CM).dat" "Sega\32X\CD\Games\[BIN-CUE]"
move "Sega 32X - CD - Games - [IMG] (TOSEC-v2013-04-10_CM).dat" "Sega\32X\CD\Games\[IMG]"
move "Sega 32X - CD - Games - [ISO] (TOSEC-v2022-06-08_CM).dat" "Sega\32X\CD\Games\[ISO]"
move "Sega Chihiro - Games (TOSEC-v2022-06-23_CM).dat" "Sega\Chihiro\Games"
move "Sega Dreamcast - Applications (TOSEC-v2022-12-28_CM).dat" "Sega\Dreamcast\Applications"
move "Sega Dreamcast - Firmware (TOSEC-v2017-07-05_CM).dat" "Sega\Dreamcast\Firmware"
move "Sega Dreamcast - Games - Dev Builds - [BIN] (TOSEC-v2022-07-03_CM).dat" "Sega\Dreamcast\Games\Dev Builds\[BIN]"
move "Sega Dreamcast - Games - Dev Builds - [ISO] (TOSEC-v2022-06-26_CM).dat" "Sega\Dreamcast\Games\Dev Builds\[ISO]"
move "Sega Dreamcast - Games - JP (TOSEC-v2022-12-20_CM).dat" "Sega\Dreamcast\Games\JP"
move "Sega Dreamcast - Games - PAL (TOSEC-v2022-06-15_CM).dat" "Sega\Dreamcast\Games\PAL"
move "Sega Dreamcast - Games - US (TOSEC-v2022-12-28_CM).dat" "Sega\Dreamcast\Games\US"
move "Sega Dreamcast - Homebrew - Applications - [CDI] (TOSEC-v2022-06-08_CM).dat" "Sega\Dreamcast\Homebrew\Applications\[CDI]"
move "Sega Dreamcast - Homebrew - Compilations - [CDI] (TOSEC-v2022-12-29_CM).dat" "Sega\Dreamcast\Homebrew\Compilations\[CDI]"
move "Sega Dreamcast - Homebrew - Demos - [BIN] (TOSEC-v2012-02-27_CM).dat" "Sega\Dreamcast\Homebrew\Demos\[BIN]"
move "Sega Dreamcast - Homebrew - Demos - [CDI] (TOSEC-v2012-02-27_CM).dat" "Sega\Dreamcast\Homebrew\Demos\[CDI]"
move "Sega Dreamcast - Homebrew - Demos - [ELF] (TOSEC-v2012-02-27_CM).dat" "Sega\Dreamcast\Homebrew\Demos\[ELF]"
move "Sega Dreamcast - Homebrew - Demos - [Multipart] (TOSEC-v2012-02-27_CM).dat" "Sega\Dreamcast\Homebrew\Demos\[Multipart]"
move "Sega Dreamcast - Homebrew - Demos - [NRG] (TOSEC-v2012-02-27_CM).dat" "Sega\Dreamcast\Homebrew\Demos\[NRG]"
move "Sega Dreamcast - Homebrew - Games - [CDI] (TOSEC-v2022-06-08_CM).dat" "Sega\Dreamcast\Homebrew\Games\[CDI]"
move "Sega Dreamcast - Homebrew - Games - [GDI] (TOSEC-v2022-06-08_CM).dat" "Sega\Dreamcast\Homebrew\Games\[GDI]"
move "Sega Dreamcast - Homebrew - Games - [MDF-MDS] (TOSEC-v2022-06-08_CM).dat" "Sega\Dreamcast\Homebrew\Games\[MDF-MDS]"
move "Sega Dreamcast - Multimedia (TOSEC-v2022-12-20_CM).dat" "Sega\Dreamcast\Multimedia"
move "Sega Dreamcast - Samplers (TOSEC-v2022-12-20_CM).dat" "Sega\Dreamcast\Samplers"
move "Sega Dreamcast - Various Unverified Dumps (TOSEC-v2022-12-28_CM).dat" "Sega\Dreamcast\Various Unverified Dumps"
move "Sega Mega-CD & Sega CD - CD - Applications (TOSEC-v2014-07-01_CM).dat" "Sega\Mega-CD & Sega CD\CD\Applications"
move "Sega Mega-CD & Sega CD - CD - Bonus Discs - [IMG] (TOSEC-v2014-07-01_CM).dat" "Sega\Mega-CD & Sega CD\CD\Bonus Discs\[IMG]"
move "Sega Mega-CD & Sega CD - CD - Bonus Discs - [ISO] (TOSEC-v2014-07-01_CM).dat" "Sega\Mega-CD & Sega CD\CD\Bonus Discs\[ISO]"
move "Sega Mega-CD & Sega CD - CD - Educational - [IMG] (TOSEC-v2013-04-10_CM).dat" "Sega\Mega-CD & Sega CD\CD\Educational\[IMG]"
move "Sega Mega-CD & Sega CD - CD - Educational - [ISO] (TOSEC-v2014-07-01_CM).dat" "Sega\Mega-CD & Sega CD\CD\Educational\[ISO]"
move "Sega Mega-CD & Sega CD - CD - Games - [IMG] (TOSEC-v2014-07-01_CM).dat" "Sega\Mega-CD & Sega CD\CD\Games\[IMG]"
move "Sega Mega-CD & Sega CD - CD - Games - [ISO] (TOSEC-v2022-06-08_CM).dat" "Sega\Mega-CD & Sega CD\CD\Games\[ISO]"
move "Sega Mega-CD & Sega CD - CD - Multimedia - [IMG] (TOSEC-v2014-07-01_CM).dat" "Sega\Mega-CD & Sega CD\CD\Multimedia\[IMG]"
move "Sega Mega-CD & Sega CD - CD - Multimedia - [ISO] (TOSEC-v2014-07-01_CM).dat" "Sega\Mega-CD & Sega CD\CD\Multimedia\[ISO]"
move "Sega Mega-CD & Sega CD - CD - Samplers - [IMG] (TOSEC-v2012-09-08_CM).dat" "Sega\Mega-CD & Sega CD\CD\Samplers\[IMG]"
move "Sega Mega-CD & Sega CD - CD - Samplers - [ISO] (TOSEC-v2014-07-01_CM).dat" "Sega\Mega-CD & Sega CD\CD\Samplers\[ISO]"
move "Sega Mega-CD & Sega CD - Homebrew - Demos (TOSEC-v2022-06-08_CM).dat" "Sega\Mega-CD & Sega CD\Homebrew\Demos"
move "Sega Mega-CD & Sega CD - Homebrew - Games (TOSEC-v2022-06-08_CM).dat" "Sega\Mega-CD & Sega CD\Homebrew\Games"
move "Sega NAOMI - Applications (TOSEC-v2022-12-20_CM).dat" "Sega\NAOMI\Applications"
move "Sega NAOMI - Games (TOSEC-v2022-12-20_CM).dat" "Sega\NAOMI\Games"
move "Sega NAOMI 2 - Games (TOSEC-v2021-07-30_CM).dat" "Sega\NAOMI 2\Games"
move "Sega Saturn - Applications (TOSEC-v2020-06-12_CM).dat" "Sega\Saturn\Applications"
move "Sega Saturn - Bonus Discs (TOSEC-v2012-07-13_CM).dat" "Sega\Saturn\Bonus Discs"
move "Sega Saturn - Firmware (TOSEC-v2014-07-01_CM).dat" "Sega\Saturn\Firmware"
move "Sega Saturn - Games - [BIN] (TOSEC-v2022-06-08_CM).dat" "Sega\Saturn\Games\[BIN]"
move "Sega Saturn - Games - [ISO] (TOSEC-v2022-06-08_CM).dat" "Sega\Saturn\Games\[ISO]"
move "Sega Saturn - Homebrew - Games - [ISO] (TOSEC-v2022-06-08_CM).dat" "Sega\Saturn\Homebrew\Games\[ISO]"
move "Sega Saturn - Multimedia (TOSEC-v2020-06-19_CM).dat" "Sega\Saturn\Multimedia"
move "Sega Saturn - Samplers (TOSEC-v2020-07-10_CM).dat" "Sega\Saturn\Samplers"
move "Sega WonderMega - CD - Educational - [IMG] (TOSEC-v2013-04-10_CM).dat" "Sega\WonderMega\CD\Educational\[IMG]"
move "Sega WonderMega - CD - Educational - [ISO] (TOSEC-v2014-07-01_CM).dat" "Sega\WonderMega\CD\Educational\[ISO]"
move "Sega WonderMega - CD - Games (TOSEC-v2014-07-01_CM).dat" "Sega\WonderMega\CD\Games"
move "Sega WonderMega - CD - Samplers (TOSEC-v2012-09-08_CM).dat" "Sega\WonderMega\CD\Samplers"
move "Sinclair ZX Spectrum - CD - Compilations (TOSEC-v2017-10-03_CM).dat" "Sinclair\ZX Spectrum\CD\Compilations"
move "SNK Hyper Neo-Geo 64 - CD - Multimedia (TOSEC-v2014-06-12_CM).dat" "SNK\Hyper Neo-Geo 64\CD\Multimedia"
move "SNK Neo-Geo CD - Bonus Discs (TOSEC-v2014-06-12_CM).dat" "SNK\Neo-Geo CD\Bonus Discs"
move "SNK Neo-Geo CD - Demos (TOSEC-v2022-06-08_CM).dat" "SNK\Neo-Geo CD\Demos"
move "SNK Neo-Geo CD - Firmware (TOSEC-v2012-09-08_CM).dat" "SNK\Neo-Geo CD\Firmware"
move "SNK Neo-Geo CD - Games - [IMG] (TOSEC-v2014-06-12_CM).dat" "SNK\Neo-Geo CD\Games\[IMG]"
move "SNK Neo-Geo CD - Games - [ISO] (TOSEC-v2022-06-08_CM).dat" "SNK\Neo-Geo CD\Games\[ISO]"
move "SNK Neo-Geo CD - Games - [Multipart] (TOSEC-v2012-09-08_CM).dat" "SNK\Neo-Geo CD\Games\[Multipart]"
move "SNK Neo-Geo CD - Multimedia - [IMG] (TOSEC-v2014-06-12_CM).dat" "SNK\Neo-Geo CD\Multimedia\[IMG]"
move "SNK Neo-Geo CD - Multimedia - [ISO] (TOSEC-v2014-06-12_CM).dat" "SNK\Neo-Geo CD\Multimedia\[ISO]"
move "SNK Neo-Geo CD - Samplers - [IMG] (TOSEC-v2012-09-08_CM).dat" "SNK\Neo-Geo CD\Samplers\[IMG]"
move "SNK Neo-Geo CD - Samplers - [ISO] (TOSEC-v2014-06-12_CM).dat" "SNK\Neo-Geo CD\Samplers\[ISO]"
move "SNK Neo-Geo CD - Samplers - [Multipart] (TOSEC-v2012-09-08_CM).dat" "SNK\Neo-Geo CD\Samplers\[Multipart]"
move "Sony PlayStation - Applications (TOSEC-v2014-10-30_CM).dat" "Sony\PlayStation\Applications"
move "Sony PlayStation - Coverdiscs (TOSEC-v2014-10-30_CM).dat" "Sony\PlayStation\Coverdiscs"
move "Sony PlayStation - Demos - [BIN] (TOSEC-v2022-06-08_CM).dat" "Sony\PlayStation\Demos\[BIN]"
move "Sony PlayStation - Demos - [EXE] (TOSEC-v2012-09-08_CM).dat" "Sony\PlayStation\Demos\[EXE]"
move "Sony PlayStation - Demos - [ISO] (TOSEC-v2012-09-08_CM).dat" "Sony\PlayStation\Demos\[ISO]"
move "Sony PlayStation - Demos - [Multipart] (TOSEC-v2012-09-08_CM).dat" "Sony\PlayStation\Demos\[Multipart]"
move "Sony PlayStation - Demos - [PSX] (TOSEC-v2012-09-08_CM).dat" "Sony\PlayStation\Demos\[PSX]"
move "Sony PlayStation - Firmware (TOSEC-v2012-09-08_CM).dat" "Sony\PlayStation\Firmware"
move "Sony PlayStation - Games - [BIN] (TOSEC-v2012-09-08_CM).dat" "Sony\PlayStation\Games\[BIN]"
move "Sony PlayStation - Games - [EXE] (TOSEC-v2012-09-08_CM).dat" "Sony\PlayStation\Games\[EXE]"
move "Sony PlayStation - Games - [IMG] (TOSEC-v2012-09-08_CM).dat" "Sony\PlayStation\Games\[IMG]"
move "Sony PlayStation - Games - [ISO] (TOSEC-v2012-09-08_CM).dat" "Sony\PlayStation\Games\[ISO]"
move "Sony PlayStation - Homebrew - Games - [BIN] (TOSEC-v2022-06-08_CM).dat" "Sony\PlayStation\Homebrew\Games\[BIN]"
move "Sony PlayStation - Homebrew - Games - [ISO] (TOSEC-v2022-06-08_CM).dat" "Sony\PlayStation\Homebrew\Games\[ISO]"
move "Sony PlayStation - Samplers - [BIN] (TOSEC-v2012-09-08_CM).dat" "Sony\PlayStation\Samplers\[BIN]"
move "Sony PlayStation - Samplers - [ISO] (TOSEC-v2012-09-08_CM).dat" "Sony\PlayStation\Samplers\[ISO]"
move "Sony PlayStation 2 - Coverdiscs - [ISO] (TOSEC-v2022-12-21_CM).dat" "Sony\PlayStation 2\Coverdiscs\[ISO]"
move "Sony PlayStation 2 - Firmware (TOSEC-v2012-09-08_CM).dat" "Sony\PlayStation 2\Firmware"
move "Sony PlayStation 2 - Games - [ISO] (TOSEC-v2022-12-21_CM).dat" "Sony\PlayStation 2\Games\[ISO]"
move "Sony PlayStation 2 - Homebrew - Games - [ISO] (TOSEC-v2022-06-08_CM).dat" "Sony\PlayStation 2\Homebrew\Games\[ISO]"
move "Sony PlayStation 2 - Samplers - [ISO] (TOSEC-v2022-12-21_CM).dat" "Sony\PlayStation 2\Samplers\[ISO]"
move "Sony PlayStation Portable - Applications - [ISO] (TOSEC-v2022-12-21_CM).dat" "Sony\PlayStation Portable\Applications\[ISO]"
move "Sony PlayStation Portable - Games - [ISO] (TOSEC-v2023-01-17_CM).dat" "Sony\PlayStation Portable\Games\[ISO]"
move "Sony PlayStation Portable - Homebrew - Games - [ISO] (TOSEC-v2022-06-08_CM).dat" "Sony\PlayStation Portable\Homebrew\Games\[ISO]"
move "Sony PlayStation Portable - Samplers - [ISO] (TOSEC-v2023-01-17_CM).dat" "Sony\PlayStation Portable\Samplers\[ISO]"
move "Tomy KISS-Site - Games (TOSEC-v2014-07-01_CM).dat" "Tomy\KISS-Site\Games"
move "VM Labs Nuon - Games (TOSEC-v2017-10-03_CM).dat" "VM Labs\Nuon\Games"
move "VTech V.Flash Home Edutainment System - Educational (TOSEC-v2017-10-03_CM).dat" "VTech\V.Flash Home Edutainment System\Educational"
move "ZAPiT Games Game Wave Family Entertainment System - Games (TOSEC-v2014-07-01_CM).dat" "ZAPiT Games\Game Wave Family Entertainment System\Games"
